.\" $Id: alc.1,v 1.1 1999/09/28 10:05:44 czo Exp $

.TH alc 1 "$Date: 1999/09/28 10:05:44 $" "ASIM/LIP6" "ALLIANCE  Reference Manual"

.SH NAME
alc \- Display Alliance system environnement variables

.so man1/alc_origin.1

.SH DESCRIPTION
alc is a small script used to display Alliance environnemnt variables 

.SH SEE ALSO
.BR alliance(1).

.so man1/alc_bug_report.1

