.\" $Id: alc_origin.1,v 1.1 1999/05/31 17:30:13 alliance Exp $
.\" 
.\" Generic header for alliance man pages
.\" 
 
.SH ORIGIN
This software belongs to the
.I ALLIANCE
CAD system from the
CAO-VLSI team at 
.B ASIM/LIP6/UPMC
laboratory. 
.br
.ce
LIP6/ASIM
.br
.ce
University P. et M. Curie
.br
.ce
4, place Jussieu 
.br
.ce
75252 PARIS Cedex 05
.br
.ce
FRANCE
.br
Fax : {33/0} 1.44.27.62.86
.br
E-mail support : 
.I alliance\-support@asim.lip6.fr


