.\" $Id: algue.1,v 1.1 1999/10/12 15:42:23 czo Exp $

.TH algue 1 "$Date: 1999/10/12 15:42:23 $" "ASIM/LIP6" "ALLIANCE  Reference Manual"

.SH NAME
algue \- ALliance Graphic User Environement

.so man1/alc_origin.1

.SH DESCRIPTION
Algue is a graphical environnement that let you lauch every
Alliance tool in press button way.

.SH SEE ALSO
.BR alliance(1).

.so man1/alc_bug_report.1

