.\" $Id: ali.1,v 1.1 1999/10/12 15:42:24 czo Exp $

.TH ali 1 "$Date: 1999/10/12 15:42:24 $" "ASIM/LIP6" "ALLIANCE  Reference Manual"

.SH NAME
ali \- ALliance Information

.so man1/alc_origin.1

.SH DESCRIPTION
ali is a small script used to display Alliance environnemnt variables 

.SH EXAMPLE

Alliance settings :

MACHINE          = Linux_elf
ALLIANCE_OS      = Linux_elf
TOP              = /users/cao7/czo/cvstree/alliance/archi/Linux_elf
ALLIANCE_TOP     = /users/cao7/czo/cvstree/alliance/archi/Linux_elf
ALLIANCE_VERSION = '"3.5.9"'

DREAL_TECHNO_NAME=/users/cao7/czo/cvstree/alliance/archi/Linux_elf/etc/cmos_7.dreal
ELP_TECHNO_NAME=/users/cao7/czo/cvstree/alliance/archi/Linux_elf/etc/prol10.elp
GRAAL_TECHNO_NAME=/users/cao7/czo/cvstree/alliance/archi/Linux_elf/etc/cmos_7.graal
MBK_C4_LIB=./cellsC4
MBK_CATAL_NAME=CATAL
MBK_CATA_LIB=.:/users/cao7/czo/cvstree/alliance/archi/Linux_elf/cells/sxlib:/users/cao7/cz
o/cvstree/alliance/archi/Linux_elf/cells/padlib
MBK_IN_LO=vst
MBK_IN_PH=ap
MBK_OUT_LO=vst
MBK_OUT_PH=ap
MBK_SCALE_X=10
MBK_TARGET_LIB=/users/cao7/czo/cvstree/alliance/archi/Linux_elf/cells/sxlib
MBK_VDD=vdd
MBK_VSS=vss
MBK_WORK_LIB=.
RDS_TECHNO_NAME=/users/cao7/czo/cvstree/alliance/archi/Linux_elf/etc/cmos_7.rds
VH_BEHSFX=vbe
VH_DLYSFX=dly
VH_MAXERR=10
VH_PATSFX=pat
XFSM_PARAM_NAME=/users/cao7/czo/cvstree/alliance/archi/Linux_elf/etc/xfsm.par
XPAT_PARAM_NAME=/users/cao7/czo/cvstree/alliance/archi/Linux_elf/etc/xpat.par

.SH SEE ALSO
.BR alliance(1).

.so man1/alc_bug_report.1

