.\"   $Id: MBK_FILTER_SFX.1,v 1.1 1999/10/13 09:57:12 czo Exp $

.TH MBK_FILTER_SFX 1 "October 1, 1999" "ASIM/LIP6" "MBK ENVIRONMENT VARIABLES"

.SH NAME
MBK_FILTER_SFX \- define the input\/output filter suffixe.

.so man1/alc_origin.1

.SH DESCRIPTION
\fBMBK_FILTER_SFX\fP sets the input\/output filter suffixe.

.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
	setenv MBK_FILTER_SFX ".gz"
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR MBK_IN_FILTER (1),
.BR MBK_OUT_FILTER (1).


.so man1/alc_bug_report.1

