.\"   $Id: MBK_OUT_FILTER.1,v 1.1 1999/10/13 09:57:13 czo Exp $

.TH MBK_OUT_FILTER 1 "October 1, 1999" "ASIM/LIP6" "MBK ENVIRONMENT VARIABLES"

.SH NAME
MBK_OUT_FILTER \- define the input filter

.so man1/alc_origin.1

.SH DESCRIPTION
\fBMBK_OUT_FILTER\fP sets the input filter

.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
	setenv MBK_OUT_FILTER "/asim/gnu/bin/gzip -c"
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR MBK_FILTER_SFX (1),
.BR MBK_IN_FILTER (1).


.so man1/alc_bug_report.1

