.\"   $Id: vasy.1,v 1.4 2000/02/11 10:47:08 syf Exp $
.\" @(#)Labo.l 2.2 95/09/24 UPMC; Author: Jacomme L.
.pl -.4
.TH VASY 1 "November 26, 1999" "ASIM/LIP6" "CAO\-VLSI Reference Manual"
.SH NAME
.TP
VASY \- VHDL Analyzer for Synthesis
.so man1/alc_origin.1
.SH SYNOPSIS
.TP
\f4vasy \-V|v|a|s|S [-I input_format] input_name [output_name]
.br
.SH DESCRIPTION
.br
\fBVASY\fp is a VHDL Analyzer for Synthesis.
\fBVASY\fp performs a semantic analysis of a VHDL RTL description 
\fBinput_name\fP, with a VHDL subset much more extended than the Alliance one
(see vasy(5) for more details), and identifies with precision all the 
memorizing elements and tristate buffers.
.br
After this analysis, \fBVASY\fp drives an equivalent description
\fBoutput_name\fP (in Verilog or VHDL format) accepted by most of
synthesis tools.
.br

.SH ENVIRONMENT VARIABLES
.br
.TP 10
\f4MBK_WORK_LIB\fR(1)
indicates the path to the read/write directory for the session.
.br

.SH OPTIONS
.TP 10
\f4\-V\fP
Verbose mode on.
Each step of the analysis is displayed on the standard output.
.TP 10
\f4\-v\fP
Drives an equivalent description in \fBVerilog\fP format.
.TP 10
\f4\-a\fP
Drives an equivalent description in Alliance VHDL format \fBvbe\fP(5) or \fBvst\fP(5)
.TP 10
\f4\-s\fP
Drives an equivalent VHDL description (with the extention \fB.vhd\fP)
accepted by most of industrial synthesis tools.
.TP 10
\f4\-S\fP
Uses Std_logic instead of Bit (taken into account only with option -s).
.TP 10
\f4\-I\fP
Specifies the VHDL input format such as Alliance VHDL format \fBvbe\fP(5),
\fBvst\fP(5) or industrial VHDL format \fBvhd\fP or \fBvhdl\fP.
.ti 7

.SH SEE ALSO
.BR vasy (5),
.BR vbe (5),
.BR vhdl (5),
.BR asimut (1),
.BR MBK_WORK_LIB (1).

.so man1/alc_bug_report.1

