#! /bin/sh
# Efface $HOME/labo 
# $Id: alc_link_labo_sce,v 1.1 1999/09/09 14:24:53 czo Exp $


TARGETS="Linux_elf Solaris SunOS"

echo "==> Exporting $LOGNAME on $TARGETS architectures"

echo "==> Cleaning $HOME/labo"

        for i in $TARGETS sparc sun pc linux dec ; do
	    rm -rf $HOME/labo/$i
	done

echo "==> Cleaning $HOME/labo/sce"
    cd $HOME/labo/sce/
    make clean
	
ROOT=labo
for ARCHI in $TARGETS
do
  echo "==> link rep $ARCHI"
  for REP in bin obj lib include
  do
   mkdir -p $HOME/labo/$ARCHI/$REP
  done
done

echo "==> Making links..."
	for i in $TARGETS; do
		for j in `ls $HOME/labo/sce`; do
			ln $HOME/labo/sce/$j $HOME/labo/$i/obj
		done
	done

echo "==> Done."

