#!/bin/tcsh -f
date +"                              Labo cao-vlsi, le %a %d %h 19%y a %H:%M" 
if ( "$1" == "" ) then
	echo "install prend comme premier parametre le nom de l'outil1 a installer"
	exit
endif
if ( "$2" == "" ) then
	echo "install prend comme deuxieme parametre le nom de l'utilisateur qui installe"
	exit
endif
echo " "
echo "Compte-rendu d'installation de l'outil1 $1 faite pour $2"
echo " "
set HOME=$1
set OUTIL=`basename $HOME`
set PCLIST="varese xenakis"
#set LINUXLIST="cherry morton bechet waller carter parker silver konitz"
set LINUXLIST="cherry morton bechet waller carter parker silver konitz"

# Installation des executables
echo "======================================================================="
echo "                             Executables                               "
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
foreach archi (sparc dec pc linux)
	echo -n " + $archi        	: "
	rsh -n house "/users/outil1/generic/genspabin $HOME/labo/$archi/bin /users/soft5/labo_$archi/bin"
end

foreach ordi ($PCLIST)
	echo -n " + pc [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspabin $HOME/labo/pc/bin /labo/bin"
end

foreach ordi ($LINUXLIST)
	echo -n " + linux [$ordi]	: "
	rsh -n $ordi "/users/outil1/generic/genspabin $HOME/labo/linux/bin /labo/bin"
end

# Installation des librairies
echo "======================================================================="
echo "                             Librairies                                "
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
foreach archi (sparc dec pc linux)
	echo -n " + $archi       	: "
	rsh -n house "/users/outil1/generic/genspalib $HOME/labo/$archi/lib /users/soft5/labo_$archi/lib"
end

foreach ordi ($PCLIST)
        echo -n " + pc [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspalib $HOME/labo/pc/lib /labo/lib"
end

foreach ordi ($LINUXLIST)
        echo -n " + linux [$ordi]	: "
        rsh -n $ordi "/users/outil1/generic/genlnxlib $HOME/labo/linux/lib /labo/lib"
end

# Installation des includes
echo "======================================================================="
echo "                             Includes                                  "
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
foreach archi (sparc dec pc linux)
	echo -n " + $archi         	: "
	rsh -n house "/users/outil1/generic/genspabin $HOME/labo/$archi/include /users/soft5/labo_$archi/include"
end

foreach ordi ($PCLIST)
	echo -n " + pc [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspabin $HOME/labo/pc/include /labo/include"
end

foreach ordi ($LINUXLIST)
	echo -n " + linux [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspabin $HOME/labo/linux/include /labo/include"
end

# Installation des etcaetera
echo "======================================================================="
echo "                             Et Caetera                                "
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
echo -n " + sparc, dec, pc, linux : "
rsh -n house "/users/outil1/generic/genspabin $HOME/labo/etc /labo/etc"

foreach ordi ($PCLIST)
	echo -n " + pc [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspabin $HOME/labo/etc /labo/etc"
end

foreach ordi ($LINUXLIST)
	echo -n " + linux [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspabin $HOME/labo/etc /labo/etc"
end

# Installation des cellules
echo "======================================================================="
echo "                             Cellules                                  "
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
echo -n " + sparc, dec, pc, linux : "
rsh -n house "/users/outil1/generic/genspabin $HOME/labo/cells /labo/cells/$OUTIL"

foreach ordi ($PCLIST)
	echo -n " + pc [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspabin $HOME/labo/cells /labo/cells/$OUTIL"
end

foreach ordi ($LINUXLIST)
	echo -n " + linux [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspabin $HOME/labo/cells /labo/cells/$OUTIL"
end

# Installation des pages du manuel
echo "======================================================================="
echo "                             ManPages (...mann)                        "
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
echo -n " + sparc, dec, pc, linux : "
rsh -n house "/users/outil1/generic/genspaman $HOME/labo/man /labo/man"

foreach ordi ($PCLIST)
	echo -n " + pc [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspaman $HOME/labo/man /labo/man"
end

foreach ordi ($LINUXLIST)
	echo -n " + linux [$ordi]  	: "
	rsh -n $ordi "/users/outil1/generic/genspaman $HOME/labo/man /labo/man"
end

echo "======================================================================="
echo " "
date +"Fini d'installer le %a %d %h 19%y a %H:%M,           [pour $2]."
