.\" $Id: flatlo.1,v 1.1 2002/04/29 14:15:48 czo Exp $
.TH FLATLO 1 "October 1, 1997" "ASIM/LIP6" "ALLIANCE USER COMMANDS"

.SH NAME
\fBflatlo\fP \- FLATen LOgical figure

.so man1/alc_origin.1


.SH SYNOPSIS
.TP
\f4flatlo\fR \fIin_format out_format in_file out_file\fR

.SH DESCRIPTION
\f4flatlo\fR FLATen LOgical figure

.SH SEE ALSO
.PP
.BR mbk(1)

.so man1/alc_bug_report.1

