AC_DEFUN(AM_ALLIANCE,
[AC_REQUIRE([AM_INIT_AUTOMAKE])
echo 'ALLIANCE configuration ....'
INCLUDES=-I${ALLIANCE_TOP}/include
LIBS=-L${ALLIANCE_TOP}/lib
AC_SUBST(INCLUDES)
AC_SUBST(LIBS)

INSTALL_DATA='${INSTALL} -m 664'
AC_SUBST(INSTALL_DATA)
INSTALL_PROGRAM='${INSTALL} -m 775'
AC_SUBST(INSTALL_PROGRAM)]

AC_DEFINE_UNQUOTED(ALLIANCE_VERSION, "5.0")
)
