#!/bin/sh
#
# Filename: instool
# Copyright (C) 1999, 2000 Czo <Olivier.Sirol@lip6.fr>
# License: GPL (http://www.gnu.org/copyleft/gpl.html)
# Started: Feb 2002
# Last Change: Wednesday 27 February 2002, 11:31
# Edit Time: 0:15:25
# Description:
#
# $Id: instool,v 1.29 2002/02/27 10:32:24 czo Exp $
#

echo "Instool est desactivé."
echo ""
echo "Il faut re ecrire un truc du genre : "
echo "cd tmp"
echo "cvs co toto"
echo "configure --prefix=/asim/alliance/Linux"
echo "make install"
echo ""

