#!/bin/sh
#
# Filename: posttaginfo
# Copyright (C) 1999, 2000 Czo <Olivier.Sirol@lip6.fr>
# License: GPL (http://www.gnu.org/copyleft/gpl.html)
# Started: Sept 1999
# Last Change: Monday 06 May 2002, 15:38
# Edit Time: 1:45:15
# Description:
#
# $Id: posttaginfo,v 1.2 2002/05/06 13:39:02 czo Exp $
#
#
# The arguments passed to the command are, in order, 
# the tagname, 
# operation (add for tag, mov for tag -F, and del for tag -d), 
# repository, 
# and any remaining are pairs of filename revision. 
# A non-zero exit of the filter program will cause the tag to be aborted.
# 

TMPFILE=cvslog.$$
FINGER=`who am i | gawk '{gsub(/^[^\!]*\!/,""); print $1}'`
MAIL_SUBJECT="CVS taginfo $1"

(
(echo "==================================================================="
echo "TAG : `date`"
echo "Par : $USER"
echo "==================================================================="
echo ""
echo "$2 of $1 in $3"
shift
shift
shift
echo "$*" ) > "$TMPFILE"


cat "$TMPFILE"  | mail -s "ALC : $MAIL_SUBJECT" alliance-programmers@asim.lip6.fr

rm -f "$TMPFILE" dummy
) > /dev/null 2>&1 &

exit 0


