#!/bin/sh
#
# Filename: setperms
# Copyright (C) 1999, 2000 Czo <Olivier.Sirol@lip6.fr>
# License: GPL (http://www.gnu.org/copyleft/gpl.html)
# Started: April 2000
# Last Change: Tuesday 03 July 2001, 16:06
# Edit Time: 0:13:29
# Description:
#
# $Id: setperms,v 1.1 2001/07/03 14:07:44 czo Exp $
#

echo %%%%%%% Hello

echo "Launching chgrp and chmod ..."
find /users/soft5/newlabo/alliance-4.5.0 -type d | xargs chmod 2775
chgrp -R 30101 /users/soft5/newlabo/alliance-4.5.0
chmod -R ug+rw /users/soft5/newlabo/alliance-4.5.0

exit 0

