#! /bin/sh

YEAR_YY=`date +%y`
YEAR_YYYY=`date +%Y`
MAILL=$1

cd /users/largo2/webmastr/wwwroot/mailing-lists

/usr/local/bin/hypermail -c /users/largo1/czo/cvslargo/listes-rules/hypermail/.hmrc -p -i -u -x -l  "${MAILL} '${YEAR_YY}" -d "${MAILL}/${YEAR_YYYY}"

