#! /bin/sh

gawk '
BEGIN {FIRST=1;}
{
if (FIRST)
{
FIRST=0;
# ca cest du bug...
if ( $0 ~ /no email/ )
  gsub(/\(no email\)/,"NOMAIL");
  
YEAR=$7;
if (YEAR<1990) {YEAR=2000}
}

   print $0 >> "/tmp/hypczo/"YEAR ;
}'
