.\"   $Id: a4_dp.5,v 1.1 1999/05/31 17:30:26 alliance Exp $
.TH A4_DP 5 "October 1, 1997" "ASIM/LIP6" "FITPATH - User Cell Library"
.so man1/alc_origin.1
.SH NAME
\fBa4_dp\fP
.SH SYNOPSIS
.ft CR
.nf
\fIGenLib Call :\fP
    LOINS( "a4_dp", "insname", "i0", "i1", "i2", "i3", "o", "vdd", "vss", 0L );
.fi
.ft R
.SH DESCRIPTION
\fIVHDL Behavioral description :\fP
.ft CR
.nf

-- Interface declaration.
ENTITY  a4_dp  IS
  PORT(
         i0 : in        BIT;
         i1 : in        BIT;
         i2 : in        BIT;
         i3 : in        BIT;
          o :   out     BIT;
        vdd : in        BIT;
        vss : in        BIT
      );
END  a4_dp;

-- Architecture declaration.
ARCHITECTURE  behavior_data_flow  OF  a4_dp  IS

BEGIN
  -- Logical equations.
  o     <= (((i0 and i1) and i2) and i3);
END  behavior_data_flow;
.fi
.ft R

\fIPhysical features :\fP
.br
.ta +4n
	Cell wide : 36 lambdas, or 6 pitchs.
.br

\fITiming characteristics :\fP
.br
.ta +6n  +2n  +6n +6nR +1n    +12nR +1n

i3	:	cin	=	67	(fF)
.br
		tphh	=	885	(ps) +	2998	(ohms) x Cload (pF)
.br
		tpll	=	1940	(ps) +	2418	(ohms) x Cload (pF)
.br

i2	:	cin	=	69	(fF)
.br
		tphh	=	936	(ps) +	2998	(ohms) x Cload (pF)
.br
		tpll	=	1773	(ps) +	2418	(ohms) x Cload (pF)
.br

i1	:	cin	=	69	(fF)
.br
		tphh	=	949	(ps) +	2998	(ohms) x Cload (pF)
.br
		tpll	=	1603	(ps) +	2418	(ohms) x Cload (pF)
.br

i0	:	cin	=	69	(fF)
.br
		tphh	=	917	(ps) +	2998	(ohms) x Cload (pF)
.br
		tpll	=	1427	(ps) +	2418	(ohms) x Cload (pF)
.br
.SH SEE ALSO
.ft B
dplib(1), fpgen(1), scmap(1)
.ft R

.so man1/alc_bug_report.1

