.\"   $Id: annup_dp.5,v 1.1 1999/05/31 17:30:26 alliance Exp $
.TH ANNUP_DP 5 "October 1, 1997" "ASIM/LIP6" "FITPATH - User Cell Library"
.so man1/alc_origin.1
.SH NAME
\fBannup_dp\fP
.SH SYNOPSIS
.ft CR
.nf
\fIGenLib Call :\fP
    LOINS( "annup_dp", "insname", "i0", "i1", "i2", "i3", "o", "vdd", "vss", 0L );
.fi
.ft R
.SH DESCRIPTION
\fIVHDL Behavioral description :\fP
.ft CR
.nf

-- Interface declaration.
ENTITY  annup_dp  IS
  PORT(
         i0 : in        BIT;
         i1 : in        BIT;
         i2 : in        BIT;
         i3 : in        BIT;
          o :   out     BIT;
        vdd : in        BIT;
        vss : in        BIT
      );
END  annup_dp;

-- Architecture declaration.
ARCHITECTURE  behavior_data_flow  OF  annup_dp  IS

BEGIN
  -- Logical equations.
  o     <= not ((i0 or i1) and (i2 or i3));
END  behavior_data_flow;
.fi
.ft R

\fIPhysical features :\fP
.br
.ta +4n
	Cell wide : 30 lambdas, or 5 pitchs.
.br

\fITiming characteristics :\fP
.br
.ta +6n  +2n  +6n +6nR +1n    +12nR +1n

i3	:	cin	=	67	(fF)
.br
		tplh	=	792	(ps) +	2979	(ohms) x Cload (pF)
.br
		tphl	=	713	(ps) +	2175	(ohms) x Cload (pF)
.br

i2	:	cin	=	67	(fF)
.br
		tplh	=	851	(ps) +	2979	(ohms) x Cload (pF)
.br
		tphl	=	519	(ps) +	2175	(ohms) x Cload (pF)
.br

i1	:	cin	=	67	(fF)
.br
		tplh	=	1065	(ps) +	2979	(ohms) x Cload (pF)
.br
		tphl	=	486	(ps) +	2175	(ohms) x Cload (pF)
.br

i0	:	cin	=	66	(fF)
.br
		tplh	=	994	(ps) +	2979	(ohms) x Cload (pF)
.br
		tphl	=	660	(ps) +	2175	(ohms) x Cload (pF)
.br
.SH SEE ALSO
.ft B
dplib(1), fpgen(1), scmap(1)
.ft R

.so man1/alc_bug_report.1

