.\"   $Id: annup_y.5,v 1.1 1999/05/31 17:30:26 alliance Exp $
.pl -.4
.TH ANNUP_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B annup_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("annup_y","name","i1","i2","i3","i4","f","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity annup_y is
     port(
        i1 : in bit;
        i2 : in bit;
        i3 : in bit;
        i4 : in bit;
        f : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
    f <= ((i2 or i1) nand (i3 or i4));
   
.br
.I - Physical features
   number of grids : 5
   number of feed-through : 0
.br
   
.I - Timing caracteristics
.br
   i1 : 48 (fF)
.br
   i2 : 48 (fF)
.br
   i3 : 48 (fF)
.br
   i4 : 48 (fF)
.br

.so man1/alc_bug_report.1

