.\"   $Id: d1_y.5,v 1.1 1999/05/31 17:30:26 alliance Exp $
.pl -.4
.TH D1_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B d1_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("d1_y","name","i","t","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity d1_y is
     port(
        i : in bit;
        t : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
    t <= i;
   
.br
.I - Physical features
   number of grids : 6
   number of feed-through : 4
.br
   
.I - Timing caracteristics
.br
   i : 29 (fF)
.br

.so man1/alc_bug_report.1

