.\" @(#)Labo.5 1.0 96/10/21 UPMC; Author: LESTER A.
.pl -.4
.TH INF 5 "Oct 21 1996" "Release 1.08" "CAO\-VLSI Reference Manual"

.SH NAME
.TP 10
INF
\- YAGLE and TAS information file

.so man1/alc_origin.1

.SH DESCRIPTION
The information file should be used to help the functional abstractor YAGLE or the timing analyzer TAS. It contains information which reduces run time and avoids false errors.
The information file should have the '.inf' extension and its name must be the name of the corresponding circuit. YAGLE and TAS will take it into account if the '-i' option is used.
This file contains several sections. Each one begins with a keyword. The declaration order is not important and it is possible to use a section more than once. Seperators are blanks, tabulations or newlines and there is no difference between upper or lower case characters. A word can be surrounded by quotation marks to prevent it being interpreted as a keyword.

.SH MUTUAL EXCLUSION
If some of the circuit terminals are mutually exclusive, this should be indicated in the MUTEX section using:
.br
.TP 2
-
muxUP{term1, term2, ...}  to express that one port at most in the list is "one".
.br
.TP 2
-
muxDN{term1, term2, ...}  to express that one port at most in the list is "zero".
.br
.TP 2
-
cmpUP{term1, term2, ...} to express that one and only one port in the list is "one".
.br
.TP 2
-
cmpDN{term1, term2, ...} to express that one and only one port in the list is "zero".
.br
Each list ends with semi-colon character ';' and the section ends with the END keyword.

.br
          MUTEX
.br
          muxUP{a,...,d};
.br
          muxDN{m,...,p};
.br
          cmpUP{i,...,l};
.br
          cmpDN{x,...,z};
.br
          ...
.br
          END

.SH SIGNAL RENAMING
User can renames some signals in the RENAME section. For each signal, the old name and the new name should be given.

.br
          RENAME
.br
          existing_name : new_name  ;
.br
          *gno* : *latch_data* ;
.br
          ...
.br
          END

.br
"new_name" will replace "existing_name" in the behavioural description file. It is possible to use the joker '*'. When the names contain the string "gno", this string is replaced by the string "latch_data" (l2_y_gno_01 is replaced by l2_y_latch_data_01).

.SH BLOCKING FUNCTIONAL ANALYSIS
User can specify a list of signals which should be considered as stop points for the functional analysis phase of the disassembly. This means that any logic preceding the stop points will not be used in order to analyse the behaviour of any gate following the stop point.

.br
          STOP
.br
          sig1 ;
.br
          sig2 ;
.br
          sigs* ;
.br
          ...
.br
          END

.br
Each line ends with the semi-colon character and the section ends with the END keyword. It is possible to use the joker '*' as for signal renaming.

.SH PATH ELIMINATION
To eliminate some critical paths, a BYPASS section should be used.

.br
          BYPASS
.br
          sig1 ;
.br
          sig2 > ;
.br
          sig3 < ;
.br
          ...
.br
          END

.br
Each line ends with the semi-colon character and the section ends with the END keyword. If a signal appears with no argument, the timing analyzer eliminates all pathes which cross it. With the '>' argument, all paths which end on the signal will be supressed and with the '<' argument, all paths beginning on the signal are suppressed.

.SH CASE ANALYSIS
To perform timing analysis in a specific case, the user can apply a pattern on the netlist with the CONSTRAINT section. It contains internal or external signals constrained by "one" or "zero". The timing analyser propagates the pattern before delay estimation.

.br
          CONSTRAINT
.br
          sig1: 0;
.br
          sig2: 1;
.br
          sig3: 0;
.br
          ...
.br
          END

.br
Each line ends with the semi-colon character and the section ends with the END keyword.

.SH PRECHARGED SIGNALS
Signals whose names end in "_p" are considered to be precharged and therefore dealt with differently by the timing analyzer. If any other signals should be considered precharged these can be specified in the PRECHARGE section.

.br
          PRECHARGE
.br
          sig1 ;
.br
          sig2 ;
.br
          ~ sig3 ;
.br
          ...
.br
          END

.br
Each line ends with the semi-colon character and the section ends with the END keyword. If a signal name is preceded by the '~' character then this signal will not be treated as a precharge, this is to deal with the case of non-precharge signals whose names end in "_p".

.SH INTERMEDIARY POINTS
In order to reduce the number of critical paths identified by the timing analyzer, it can sometimes be useful to specify that certain internal signals be considered as though they were path terminals. The list of these intermediary points is specified in the INTER section. Correct choice of these signals can lead to factorization of the critical paths, and hence a significant reduction in the size of the output file generated.

.br
          INTER
.br
          sig1 ;
.br
          sig2 ;
.br
          ...
.br
          END

.br
Each line ends with the semi-colon character and the section ends with the END keyword.

.SH PATH SELECTION
Another technique for reducing the size of the critical path list is to limit the number of signals which are considered to be path terminals. The list of signals which are allowed to start a critical path is specified in the PATHIN section, and the list of signals allowed to end a critical path is specified in the PATHOUT section.

.br
          PATHIN
.br
          sig1 ;
.br
          sig2 ;
.br
          ...
.br
          END

.br
          PATHOUT
.br
          sig3 ;
.br
          sig4 ;
.br
          ...
.br
          END

.br
Each line ends with the semi-colon character and both sections end with the END keyword.

.so man1/alc_bug_rprt.1

.SH SEE ALSO
.br
yagle(1), tas(1)


