.\"   $Id: l1_y.5,v 1.1 1999/05/31 17:30:27 alliance Exp $
.pl -.4
.TH L1_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B l1_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("l1_y","name","i","l","t","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity l1_y is
     port(
        i : in bit;
        l : in bit;
        t : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
   label0 : block (l = '1')
.br
   begin
.br
     mpx_s <= guarded i;
.br
   end block;
.br
   
    t <= mpx_s;
   
.br
.I - Physical features
   number of grids : 5
   number of feed-through : 2
.br
   
.I - Timing caracteristics
.br
   i : 82 (fF)
.br
   l : 24 (fF)
.br
.br

.so man1/alc_bug_report.1

