.\"   $Id: l5s_y.5,v 1.1 1999/05/31 17:30:27 alliance Exp $
.pl -.4
.TH L5S_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B l5s_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("l5s_y","name","i0","l0","i1","l1","i2","l2","i3","l3","l4","t","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity l5s_y is
     port(
        i0 : in bit;
        l0 : in bit;
        i1 : in bit;
        l1 : in bit;
        i2 : in bit;
        l2 : in bit;
        i3 : in bit;
        l3 : in bit;
        l4 : in bit;
        t : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
   label4 : block (l4 = '1')
.br
   begin
.br
     mpx_s <= guarded '1';
.br
   end block;
.br
   
   label3 : block (l3 = '1')
.br
   begin
.br
     mpx_s <= guarded i3;
.br
   end block;
.br
   
   label2 : block (l2 = '1')
.br
   begin
.br
     mpx_s <= guarded i2;
.br
   end block;
.br
   
   label1 : block (l1 = '1')
.br
   begin
.br
     mpx_s <= guarded i1;
.br
   end block;
.br
   
   label0 : block (l0 = '1')
.br
   begin
.br
     mpx_s <= guarded i0;
.br
   end block;
.br
   
    t <= mpx_s;
   
.br
.I - Physical features
   number of grids : 11
   number of feed-through : 1
.br
   
.I - Timing caracteristics
.br
   i0 : 140 (fF)
.br
   l0 : 24 (fF)
.br
   i1 : 140 (fF)
.br
   l1 : 25 (fF)
.br
   i2 : 140 (fF)
.br
   l2 : 24 (fF)
.br
   i3 : 140 (fF)
.br
   l3 : 24 (fF)
.br
   l4 : 23 (fF)
.br
.br

.so man1/alc_bug_report.1

