.\"   $Id: ms2_y.5,v 1.1 1999/05/31 17:30:27 alliance Exp $
.pl -.4
.TH MS2_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B ms2_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("ms2_y","name","di","si","se","l","t","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity ms2_y is
     port(
        di : in bit;
        si : in bit;
        se : in bit;
        l : in bit;
        t : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
   label0 : block ((not l and not l'stable ) = '1')
.br
   begin
.br
     dff_s <= guarded not ((se and si) or (not se and di));
.br
   end block;
.br
   
    t <= not dff_s;
   
.br
.I - Physical features
   number of grids : 17
   number of feed-through : 12
.br
   
.I - Timing caracteristics
.br
   di : 78 (fF)
.br
   si : 78 (fF)
.br
   se : 121 (fF)
.br
   l : 81 (fF)
.br
.br

.so man1/alc_bug_report.1

