.\"   $Id: ms2rx_y.5,v 1.1 1999/05/31 17:30:27 alliance Exp $
.pl -.4
.TH MS2RX_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B ms2rx_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("ms2rx_y","name","di","si","se","l","r","t","f","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity ms2rx_y is
     port(
        di : in bit;
        si : in bit;
        se : in bit;
        l : in bit;
        r : in bit;
        t : out bit;
        f : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
   label1 : block ((not l and not l'stable ) = '1')
.br
   begin
.br
     dff_s <= guarded ((se and not si) or (not se and not di));
.br
   end block;
.br
   
   label0 : block (r = '1')
.br
   begin
.br
     dff_s <= guarded '1';
.br
   end block;
.br
   
    f <= dff_s;
    t <= not dff_s;
   
.br
.I - Physical features
   number of grids : 21
   number of feed-through : 13
.br
   
.I - Timing caracteristics
.br
   di : 78 (fF)
.br
   si : 78 (fF)
.br
   se : 120 (fF)
.br
   l : 84 (fF)
.br
   r : 46 (fF)
.br
.br

.so man1/alc_bug_report.1

