.\"   $Id: ms2x_dp.5,v 1.1 1999/05/31 17:30:27 alliance Exp $
.TH MS2X_DP 5 "October 1, 1997" "ASIM/LIP6" "FITPATH - User Cell Library"
.so man1/alc_origin.1
.SH NAME
\fBms2x_dp\fP
.SH SYNOPSIS
.ft CR
.nf
\fIGenLib Call :\fP
    LOINS( "ms2x_dp", "insname", "di", "si", "se", "l", "t", "f", "vdd", "vss", 0L );
.fi
.ft R
.SH DESCRIPTION
\fIVHDL Behavioral description :\fP
.ft CR
.nf

-- Interface declaration.
ENTITY  ms2x_dp  IS
  PORT(
         di : in        BIT;
         si : in        BIT;
         se : in        BIT;
          l : in        BIT;
          t :   out     BIT;
          f :   out     BIT;
        vdd : in        BIT;
        vss : in        BIT
      );
END  ms2x_dp;

-- Architecture declaration.
ARCHITECTURE  behavior_data_flow  OF  ms2x_dp  IS

  -- Internal registers.
  SIGNAL dff_s : REG_BIT REGISTER;

BEGIN
  -- Register affectations.
  label0 :BLOCK( (not l and not l'stable ) = '1' )
  BEGIN
    dff_s <= GUARDED ((not di and not se) or (not si and se));
  END BLOCK label0;

  -- Logical equations.
  f     <= dff_s;
  t     <= not dff_s;
END  behavior_data_flow;
.fi
.ft R

\fIPhysical features :\fP
.br
.ta +4n
	Cell wide : 102 lambdas, or 17 pitchs.
.br

\fITiming characteristics :\fP
.br
.ta +6n  +2n  +6n +6nR +1n    +12nR +1n

l	:	cin	=	68	(fF)
.br

se	:	cin	=	114	(fF)
.br

si	:	cin	=	70	(fF)
.br

di	:	cin	=	68	(fF)
.br
.SH SEE ALSO
.ft B
dplib(1), fpgen(1), scmap(1)
.ft R

.so man1/alc_bug_report.1

