.\"   $Id: ms_y.5,v 1.1 1999/05/31 17:30:27 alliance Exp $
.pl -.4
.TH MS_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B ms_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("ms_y","name","i","l","t","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity ms_y is
     port(
        i : in bit;
        l : in bit;
        t : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
   label0 : block ((not l and not l'stable ) = '1')
.br
   begin
.br
     dff_s <= guarded not i;
.br
   end block;
.br
   
    t <= not dff_s;
   
.br
.I - Physical features
   number of grids : 12
   number of feed-through : 9
.br
   
.I - Timing caracteristics
.br
   i : 47 (fF)
.br
   l : 81 (fF)
.br
.br

.so man1/alc_bug_report.1

