.\"   $Id: msrx_y.5,v 1.1 1999/05/31 17:30:27 alliance Exp $
.pl -.4
.TH MSRX_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B msrx_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("msrx_y","name","i","l","r","t","f","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity msrx_y is
     port(
        i : in bit;
        l : in bit;
        r : in bit;
        t : out bit;
        f : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
   label1 : block ((not l and not l'stable ) = '1')
.br
   begin
.br
     dff_s <= guarded not i;
.br
   end block;
.br
   
   label0 : block (r = '1')
.br
   begin
.br
     dff_s <= guarded '1';
.br
   end block;
.br
   
    f <= dff_s;
    t <= not dff_s;
   
.br
.I - Physical features
   number of grids : 17
   number of feed-through : 12
.br
   
.I - Timing caracteristics
.br
   i : 48 (fF)
.br
   l : 89 (fF)
.br
   r : 41 (fF)
.br
.br

.so man1/alc_bug_report.1

