.\"   $Id: mx2p_dp.5,v 1.1 1999/05/31 17:30:27 alliance Exp $
.TH MX2P_DP 5 "October 1, 1997" "ASIM/LIP6" "FITPATH - User Cell Library"
.so man1/alc_origin.1
.SH NAME
\fBmx2p_dp\fP
.SH SYNOPSIS
.ft CR
.nf
\fIGenLib Call :\fP
    LOINS( "mx2p_dp", "insname", "i0", "l0", "i1", "l1", "t", "vdd", "vss", 0L );
.fi
.ft R
.SH DESCRIPTION
\fIVHDL Behavioral description :\fP
.ft CR
.nf

-- Interface declaration.
ENTITY  mx2p_dp  IS
  PORT(
         i0 : in        BIT;
         l0 : in        BIT;
         i1 : in        BIT;
         l1 : in        BIT;
          t :   out     BIT;
        vdd : in        BIT;
        vss : in        BIT
      );
END  mx2p_dp;

-- Architecture declaration.
ARCHITECTURE  behavior_data_flow  OF  mx2p_dp  IS

BEGIN
  -- Logical equations.
  t     <= ((l1 and i1) or (l0 and i0));
END  behavior_data_flow;
.fi
.ft R

\fIPhysical features :\fP
.br
.ta +4n
	Cell wide : 48 lambdas, or 8 pitchs.
.br

\fITiming characteristics :\fP
.br
.ta +6n  +2n  +6n +6nR +1n    +12nR +1n

l1	:	cin	=	54	(fF)
.br
		tphh	=	1460	(ps) +	1499	(ohms) x Cload (pF)
.br
		tpll	=	1663	(ps) +	1209	(ohms) x Cload (pF)
.br

i1	:	cin	=	54	(fF)
.br
		tphh	=	1577	(ps) +	1499	(ohms) x Cload (pF)
.br
		tpll	=	1574	(ps) +	1209	(ohms) x Cload (pF)
.br

l0	:	cin	=	54	(fF)
.br
		tphh	=	1115	(ps) +	1499	(ohms) x Cload (pF)
.br
		tpll	=	1607	(ps) +	1209	(ohms) x Cload (pF)
.br

i0	:	cin	=	54	(fF)
.br
		tphh	=	1209	(ps) +	1499	(ohms) x Cload (pF)
.br
		tpll	=	1514	(ps) +	1209	(ohms) x Cload (pF)
.br
.SH SEE ALSO
.ft B
dplib(1), fpgen(1), scmap(1)
.ft R

.so man1/alc_bug_report.1

