.\"   $Id: nao3_y.5,v 1.1 1999/05/31 17:30:27 alliance Exp $
.pl -.4
.TH NAO3_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B nao3_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("nao3_y","name","i0","i1","i2","f","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity nao3_y is
     port(
        i0 : in bit;
        i1 : in bit;
        i2 : in bit;
        f : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
    f <= ((i0 and i1) nor i2);
   
.br
.I - Physical features
   number of grids : 4
   number of feed-through : 0
.br
   
.I - Timing caracteristics
.br
   i0 : 56 (fF)
.br
   i1 : 56 (fF)
.br
   i2 : 48 (fF)
.br

.so man1/alc_bug_report.1

