.\"   $Id: neou4_dp.5,v 1.1 1999/05/31 17:30:28 alliance Exp $
.TH NEOU4_DP 5 "October 1, 1997" "ASIM/LIP6" "FITPATH - User Cell Library"
.so man1/alc_origin.1
.SH NAME
\fBneou4_dp\fP
.SH SYNOPSIS
.ft CR
.nf
\fIGenLib Call :\fP
    LOINS( "neou4_dp", "insname", "i0", "i1", "i2", "i3", "f", "vdd", "vss", 0L );
.fi
.ft R
.SH DESCRIPTION
\fIVHDL Behavioral description :\fP
.ft CR
.nf

-- Interface declaration.
ENTITY  neou4_dp  IS
  PORT(
         i0 : in        BIT;
         i1 : in        BIT;
         i2 : in        BIT;
         i3 : in        BIT;
          f :   out     BIT;
        vdd : in        BIT;
        vss : in        BIT
      );
END  neou4_dp;

-- Architecture declaration.
ARCHITECTURE  behavior_data_flow  OF  neou4_dp  IS

BEGIN
  -- Logical equations.
  f     <= not ((i0 and i1) or (i2 or i3));
END  behavior_data_flow;
.fi
.ft R

\fIPhysical features :\fP
.br
.ta +4n
	Cell wide : 30 lambdas, or 5 pitchs.
.br

\fITiming characteristics :\fP
.br
.ta +6n  +2n  +6n +6nR +1n    +12nR +1n

i3	:	cin	=	60	(fF)
.br
		tplh	=	925	(ps) +	4206	(ohms) x Cload (pF)
.br
		tphl	=	475	(ps) +	2418	(ohms) x Cload (pF)
.br

i2	:	cin	=	59	(fF)
.br
		tplh	=	1052	(ps) +	4206	(ohms) x Cload (pF)
.br
		tphl	=	679	(ps) +	2418	(ohms) x Cload (pF)
.br

i1	:	cin	=	70	(fF)
.br
		tplh	=	1209	(ps) +	4206	(ohms) x Cload (pF)
.br
		tphl	=	804	(ps) +	1803	(ohms) x Cload (pF)
.br

i0	:	cin	=	69	(fF)
.br
		tplh	=	1368	(ps) +	4206	(ohms) x Cload (pF)
.br
		tphl	=	700	(ps) +	1803	(ohms) x Cload (pF)
.br
.SH SEE ALSO
.ft B
dplib(1), fpgen(1), scmap(1)
.ft R

.so man1/alc_bug_report.1

