.\"   $Id: nmx2_y.5,v 1.1 1999/05/31 17:30:28 alliance Exp $
.pl -.4
.TH NMX2_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B nmx2_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("nmx2_y","name","j0","j1","i0","i1","f","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity nmx2_y is
     port(
        j0 : in bit;
        j1 : in bit;
        i0 : in bit;
        i1 : in bit;
        f : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
    f <= ((j0 and j1) nor (i0 and i1));
   
.br
.I - Physical features
   number of grids : 6
   number of feed-through : 1
.br
   
.I - Timing caracteristics
.br
   j0 : 78 (fF)
.br
   j1 : 78 (fF)
.br
   i0 : 78 (fF)
.br
   i1 : 78 (fF)
.br

.so man1/alc_bug_report.1

