.\"   $Id: o2_y.5,v 1.1 1999/05/31 17:30:28 alliance Exp $
.pl -.4
.TH O2_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B o2_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("o2_y","name","i0","i1","t","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity o2_y is
     port(
        i0 : in bit;
        i1 : in bit;
        t : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
    t <= (i0 or i1);
   
.br
.I - Physical features
   number of grids : 4
   number of feed-through : 1
.br
   
.I - Timing caracteristics
.br
   i0 : 51 (fF)
.br
   i1 : 51 (fF)
.br

.so man1/alc_bug_report.1

