.\"   $Id: one_dp.5,v 1.1 1999/05/31 17:30:28 alliance Exp $
.TH ONE_DP 5 "October 1, 1997" "ASIM/LIP6" "FITPATH - User Cell Library"
.so man1/alc_origin.1
.SH NAME
\fBone_dp\fP
.SH SYNOPSIS
.ft CR
.nf
\fIGenLib Call :\fP
    LOINS( "one_dp", "insname", "o", "vdd", "vss", 0L );
.fi
.ft R
.SH DESCRIPTION
\fIVHDL Behavioral description :\fP
.ft CR
.nf

-- Interface declaration.
ENTITY  one_dp  IS
  PORT(
          o :   out     BIT;
        vdd : in        BIT;
        vss : in        BIT
      );
END  one_dp;

-- Architecture declaration.
ARCHITECTURE  behavior_data_flow  OF  one_dp  IS

BEGIN
  -- Logical equations.
  o     <= '1';
END  behavior_data_flow;
.fi
.ft R

\fIPhysical features :\fP
.br
.ta +4n
	Cell wide : 12 lambdas, or 2 pitchs.
.br

\fITiming characteristics :\fP
.br
.ta +6n  +2n  +6n +6nR +1n    +12nR +1n

		rup	=	2637	(ohms)
.br
		rdown	=	0	(ohms)
.br
.SH SEE ALSO
.ft B
dplib(1), fpgen(1), scmap(1)
.ft R

.so man1/alc_bug_report.1

