.\" $Id: pck_sp.5,v 1.1 1999/05/31 17:30:26 alliance Exp $
.pl -.4
.TH pck_sp 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B pck_sp

.so man1/alc_origin.1

.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("pck_sp","name","pad","ck","vdde","vddi","vsse","vssi",0);
.SH DESCRIPTION
.I - Interface
   entity pck_sp is
     port(
        pad : in bit;
        ck : out bit;
        vdde : in bit;
        vddi : in bit;
        vsse : in bit;
        vssi : in bit);
.br
.I - Logical description
.br
    ck <= pad;
   
.br
.I - Physical features
   number of grids : 341
   number of feed-through : 0
.br
   
.I - Timing caracteristics
.br
   pad : 1326 (fF)
        tphh = 228 (ps) + 68 (Ohms) x Cload (pF)
        tpll = 1443 (ps) + 58 (Ohms) x Cload (pF)
.br
.br

.so man1/alc_bug_report.1
