.\" $Id: pi_sp.5,v 1.1 1999/05/31 17:30:26 alliance Exp $
.pl -.4
.TH pi_sp 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B pi_sp

.so man1/alc_origin.1

.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("pi_sp","name","pad","t","ck","vdde","vddi","vsse","vssi",0);
.SH DESCRIPTION
.I - Interface
   entity pi_sp is
     port(
        pad : in bit;
        t : out bit;
        ck : in bit;
        vdde : in bit;
        vddi : in bit;
        vsse : in bit;
        vssi : in bit);
.br
.I - Logical description
.br
    t <= pad;
   
.br
.I - Physical features
   number of grids : 341
   number of feed-through : 0
.br
   
.I - Timing caracteristics
.br
   pad : 654 (fF)
        tphh = 233 (ps) + 273 (Ohms) x Cload (pF)
        tpll = 1487 (ps) + 234 (Ohms) x Cload (pF)
.br
.br
.br

.so man1/alc_bug_report.1
