.\"   $Id: sum_y.5,v 1.1 1999/05/31 17:30:28 alliance Exp $
.pl -.4
.TH SUM_Y 5 "October 1, 1997" "ASIM/LIP6" "STANDARD-CELL LIBRARY"
.SH NAME
.B sum_y
.so man1/alc_origin.1
.SH SYNOPSIS
.B Genlib call :
.br
  LOINS("sum_y","name","pi","ci","si","c0b","f","vdd","vss",0);
.SH DESCRIPTION
.I - Interface
   entity sum_y is
     port(
        pi : in bit;
        ci : in bit;
        si : in bit;
        c0b : in bit;
        f : out bit;
        vdd : in bit;
        vss : in bit);
.br
.I - Logical description
.br
    f <= not (((si and pi) and ci) or (c0b and ((si or pi) or ci)));
   
.br
.I - Physical features
   number of grids : 8
   number of feed-through : 3
.br
   
.I - Timing caracteristics
.br
   pi : 102 (fF)
.br
   ci : 99 (fF)
.br
   si : 96 (fF)
.br
   c0b : 52 (fF)
.br

.so man1/alc_bug_report.1

