.\"   $Id: sum_dp.5,v 1.1 1999/05/31 17:30:28 alliance Exp $
.TH SUM_DP 5 "October 1, 1997" "ASIM/LIP6" "FITPATH - User Cell Library"
.so man1/alc_origin.1
.SH NAME
\fBsum_dp\fP
.SH SYNOPSIS
.ft CR
.nf
\fIGenLib Call :\fP
    LOINS( "sum_dp", "insname", "pi", "ci", "si", "c0b", "f", "vdd", "vss", 0L );
.fi
.ft R
.SH DESCRIPTION
\fIVHDL Behavioral description :\fP
.ft CR
.nf

-- Interface declaration.
ENTITY  sum_dp  IS
  PORT(
         pi : in        BIT;
         ci : in        BIT;
         si : in        BIT;
        c0b : in        BIT;
          f :   out     BIT;
        vdd : in        BIT;
        vss : in        BIT
      );
END  sum_dp;

-- Architecture declaration.
ARCHITECTURE  behavior_data_flow  OF  sum_dp  IS

BEGIN
  -- Logical equations.
  f     <= not (((si and pi) and ci) or (c0b and ((si or pi) or ci)));
END  behavior_data_flow;
.fi
.ft R

\fIPhysical features :\fP
.br
.ta +4n
	Cell wide : 48 lambdas, or 8 pitchs.
.br

\fITiming characteristics :\fP
.br
.ta +6n  +2n  +6n +6nR +1n    +12nR +1n

c0b	:	cin	=	54	(fF)
.br
		tplh	=	940	(ps) +	4837	(ohms) x Cload (pF)
.br
		tphl	=	452	(ps) +	2702	(ohms) x Cload (pF)
.br

si	:	cin	=	101	(fF)
.br
		tplh	=	1946	(ps) +	6829	(ohms) x Cload (pF)
.br
		tphl	=	1052	(ps) +	3588	(ohms) x Cload (pF)
.br

ci	:	cin	=	99	(fF)
.br
		tplh	=	2381	(ps) +	6829	(ohms) x Cload (pF)
.br
		tphl	=	1271	(ps) +	3588	(ohms) x Cload (pF)
.br

pi	:	cin	=	104	(fF)
.br
		tplh	=	2242	(ps) +	6829	(ohms) x Cload (pF)
.br
		tphl	=	1180	(ps) +	3588	(ohms) x Cload (pF)
.br
.SH SEE ALSO
.ft B
dplib(1), fpgen(1), scmap(1)
.ft R

.so man1/alc_bug_report.1

