.\"   $Id: ts_dp.5,v 1.1 1999/05/31 17:30:28 alliance Exp $
.TH TS_DP 5 "October 1, 1997" "ASIM/LIP6" "FITPATH - User Cell Library"
.so man1/alc_origin.1
.SH NAME
\fBts_dp\fP
.SH SYNOPSIS
.ft CR
.nf
\fIGenLib Call :\fP
    LOINS( "ts_dp", "insname", "i", "o", "v", "vdd", "vss", 0L );
.fi
.ft R
.SH DESCRIPTION
\fIVHDL Behavioral description :\fP
.ft CR
.nf

-- Interface declaration.
ENTITY  ts_dp  IS
  PORT(
          i : in        BIT;
          o :   out MUX_BIT BUS;
          v : in        BIT;
        vdd : in        BIT;
        vss : in        BIT
      );
END  ts_dp;

-- Architecture declaration.
ARCHITECTURE  behavior_data_flow  OF  ts_dp  IS

BEGIN
  -- Bus affectations.
  label0 :BLOCK( v = '1' )
  BEGIN
    o <= GUARDED i;
  END BLOCK label0;
END  behavior_data_flow;
.fi
.ft R

\fIPhysical features :\fP
.br
.ta +4n
	Cell wide : 54 lambdas, or 9 pitchs.
.br

\fITiming characteristics :\fP
.br
.ta +6n  +2n  +6n +6nR +1n    +12nR +1n

v	:	cin	=	99	(fF)
.br
		tphl	=	1148	(ps) +	657	(ohms) x Cload (pF)
.br
		tphh	=	1145	(ps) +	849	(ohms) x Cload (pF)
.br

i	:	cin	=	47	(fF)
.br
		tphh	=	1281	(ps) +	849	(ohms) x Cload (pF)
.br
		tpll	=	1370	(ps) +	657	(ohms) x Cload (pF)
.br
.SH SEE ALSO
.ft B
dplib(1), fpgen(1), scmap(1)
.ft R

.so man1/alc_bug_report.1

