.\"   $Id: xr2_dp.5,v 1.1 1999/05/31 17:30:28 alliance Exp $
.TH XR2_DP 5 "October 1, 1997" "ASIM/LIP6" "FITPATH - User Cell Library"
.so man1/alc_origin.1
.SH NAME
\fBxr2_dp\fP
.SH SYNOPSIS
.ft CR
.nf
\fIGenLib Call :\fP
    LOINS( "xr2_dp", "insname", "i0", "i1", "o", "vdd", "vss", 0L );
.fi
.ft R
.SH DESCRIPTION
\fIVHDL Behavioral description :\fP
.ft CR
.nf

-- Interface declaration.
ENTITY  xr2_dp  IS
  PORT(
         i0 : in        BIT;
         i1 : in        BIT;
          o :   out     BIT;
        vdd : in        BIT;
        vss : in        BIT
      );
END  xr2_dp;

-- Architecture declaration.
ARCHITECTURE  behavior_data_flow  OF  xr2_dp  IS

BEGIN
  -- Logical equations.
  o     <= not (((not i1 and not i0) or (not i0 and not i1)) or (i1 and i0));
END  behavior_data_flow;
.fi
.ft R

\fIPhysical features :\fP
.br
.ta +4n
	Cell wide : 48 lambdas, or 8 pitchs.
.br

\fITiming characteristics :\fP
.br
.ta +6n  +2n  +6n +6nR +1n    +12nR +1n

i1	:	cin	=	131	(fF)
.br
		tplh	=	757	(ps) +	2979	(ohms) x Cload (pF)
.br
		tphl	=	634	(ps) +	2418	(ohms) x Cload (pF)
.br
		tphh	=	1269	(ps) +	2979	(ohms) x Cload (pF)
.br
		tpll	=	1176	(ps) +	2418	(ohms) x Cload (pF)
.br

i0	:	cin	=	131	(fF)
.br
		tplh	=	861	(ps) +	2979	(ohms) x Cload (pF)
.br
		tphl	=	545	(ps) +	2418	(ohms) x Cload (pF)
.br
		tphh	=	1059	(ps) +	2979	(ohms) x Cload (pF)
.br
		tpll	=	1217	(ps) +	2418	(ohms) x Cload (pF)
.br
.SH SEE ALSO
.ft B
dplib(1), fpgen(1), scmap(1)
.ft R

.so man1/alc_bug_report.1

