.\" $Id: x2y.1,v 1.1 2002/04/29 14:15:51 czo Exp $
.TH X2Y 1 "October 1, 1997" "ASIM/LIP6" "ALLIANCE USER COMMANDS"

.SH NAME
\fBx2y\fP \- Netlist Format converter

.so man1/alc_origin.1


.SH SYNOPSIS
.TP
\f4x2y\fR \fIin_format out_format in_file out_file\fR

.SH DESCRIPTION
\f4x2y\fR is a netlist format converter

.SH SEE ALSO
.PP
.BR mbk(1)

.so man1/alc_bug_report.1

