#!/bin/sh
#sed  's/\([A-Za-z_]*\)[ \t]*(\(.\))/<A HREF=\1.\2.html>\1(\2)<\/A>/g'
#for MANF in `find . -type f`
for MANF in ./man1/alliance_*.1
do
 MAN_NAME=`basename $MANF`
 echo %%%%%%%%%%%% process $MANF
 (echo ".ll 8.1i"; cat $MANF ) | /usr/bin/gtbl | /usr/bin/groff -Tascii -mandoc | rman -f html -l $MAN_NAME -r '%s.%s.html' > htmlman/$MAN_NAME.html

done
