#!/bin/sh
#
# Author      : Olivier.Sirol@lip6.fr
# Date        : dec 1998
# Description :
#
# (C) Czo 1998,99
# This code is released under GPL
#
# $Id: mk-distrib,v 1.1 2002/04/29 14:15:31 czo Exp $
#
(
date

FTPDIR=/users/largo2/ftp/pub/alliance/unstable/distribution
DISTRIBDIR=/users/soft5/newlabo/distrib
RPMTOPDIR=/users/cao/czo/rpm
TMPDIR=tmp-$$

CVSROOT=/users/outil/alliance/cvsroot
export CVSROOT

echo "--> mk-distrib"

cd $DISTRIBDIR

echo "Removing old test..."
mv alliance $TMPDIR
rm -fr  $TMPDIR &

echo "Checkout CVS sources..."
cvs co alliance

echo "Multibuild..."
cd $DISTRIBDIR/alliance/sources/distrib
./multibuild

if [ $? -ne 0 ] ; then echo "Multibuild Error, exiting" ; exit 4 ; fi

cd $DISTRIBDIR

echo "--> del sce-*"
rm -fr alliance/sce-*

echo "--> del CVS-*"
find alliance -type d -name CVS | xargs rm -fr dummy 

VER=`cat alliance/share/etc/libraries.mk | grep ALLIANCE_VERSION | perl -pe 's§^.*?"§§ ; s§".*?$§§'`

DATE=`date +%Y%m%d`

FILES=`find alliance -maxdepth 1 -type f`

GZIP="--best"; export GZIP

echo "--> tar"

tar czf $FTPDIR/alliance-$VER-$DATE-sources.tar.gz  $FILES alliance/share alliance/sources

tar czf $FTPDIR/alliance-$VER-$DATE-i386-linux-2.4.9-glibc2.tar.gz $FILES alliance/share alliance/archi/Linux

#tar czf $FTPDIR/alliance-$VER-$DATE-sparc-solaris-2.7.tar.gz $FILES alliance/share alliance/archi/Solaris

# tar czf $FTPDIR/alliance-$VER-$DATE-sparc-sunos-4.1.4.tar.gz $FILES alliance/share alliance/archi/SunOS

echo "--> rpm"

cat $DISTRIBDIR/alliance/sources/distrib/alliance.spec | sed s§MULTIVER§$VER§ | sed s§MULTIDATE§$DATE§ > /users/cao/czo/rpm/SPECS/alliance.spec

rpm -ba /users/cao/czo/rpm/SPECS/alliance.spec 

cp $RPMTOPDIR/RPMS/i386/alliance-$VER-$DATE.i386.rpm $FTPDIR
#echo "cp sur ftp largo"


#echo "Rsync in 2 days..."
#sleep 2d
#rsync -acz --delete --stats /users/soft5/newlabo/test largo:/users/largo2/ftp/pub/alliance/distribution/latest-cvs/binaries
date
) 2>&1 | tee mk-distrib-$$.log &
