.\" $Id: alc_origin.1,v 1.3 2003/02/05 16:10:44 czo Exp $
.\" 
.\" Generic header for alliance man pages
.\" 
 
.SH ORIGIN
This software belongs to the 
\f4 ALLIANCE CAD\fP 
system from the
CAO-VLSI team at 
.B ASIM/LIP6/UPMC
laboratory. 

.br
Web :
.I http://asim.lip6.fr/alliance/
.br
E-mail : 
.I alliance\-users@asim.lip6.fr
