.\" $Id: alc_bug_report.1,v 1.1 2002/05/07 10:39:30 czo Exp $
.\" 
.\" Generic footer for alliance man pages
.\" 

.SH BUG REPORT

This tool is under development at the
.B ASIM/LIP6/UPMC
laboratory, cao-vlsi research team.
.br
We need your feedbak to improve documentation and tools.
.br
If you find bugs, please fill-in the form at
.br
.I http://www\-asim.lip6.fr/alliance/support/bug\-report/ 
.br
Thanks for doing this.
