.\"   $Id: action.3,v 1.1 1999/05/31 17:30:16 alliance Exp $
.\" @(#)ACTION.2 1.9 Sep 15 1992 UPMC ; VUONG H.N.
.TH ACTION 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBaction\fP, GENPAT Package

.SH SYNOPSYS
.PP
.nf
action("instruction");
.fi

.so man1/alc_origin.1
.SH PARAMETERS
.PP
.TP 10
\fIinstruction\fP
The action asked.
There is only one instruction available : S, to save the current state of the circuit at the end of the simulation.

.SH DESCRIPTION
.PP
To give instructions to the simulator.

.SH EXAMPLES
.PP
.nf
action("S");
.fi

.SH SEE ALSO
.PP
genpat(1), pat(5)


.SH DIAGNOSTICS
.PP
All the ports used in an array, if they are declared elsewhere must be declared before the declaration of the Array.


.so man1/alc_bug_report.1

