.\"   $Id: ACTION.3,v 1.2 2001/04/25 08:31:47 czo Exp $
.\" @(#)ACTION.2 2.20 Sep 09 1993 UPMC ; VUONG H.N. 
.TH ACTION 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBACTION\fP \- GENPAT Package

.SH SYNOPSYS
.PP
.nf
ACTION("instruction");
.fi

.so man1/alc_origin.1
.SH PARAMETERS
.PP
.TP 10
\fIinstruction\fP
The action asked.
There is only one instruction available : S, to save the current state of the circuit at the end of the simulation.

.SH DESCRIPTION
.PP
To give instructions to the simulator.

.SH EXAMPLES
.PP
.nf
ACTION("S");
.fi

.SH SEE ALSO
.PP
genpat(1), pat(5)


.so man1/alc_bug_report.1

