.\"   $Id: addauthelem.3,v 1.1 1999/05/31 17:30:17 alliance Exp $
.\" @(#)addauthelem.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH ADDAUTHELEM 3 "October 1, 1997" "ASIM/LIP6" "AUT FUNCTIONS"
.SH NAME
addauthelem \- adds an element in the hash table. 
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "aut101.h"
authelem \(**addauthelem( HashTable, Key, Value )
  authtable \(**HashTable;
  char      \(**Key;
  long       Value;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIHashTable\fP
Pointer to the hash table where to add an element in.
.TP
\fIKey\fP
The hash element key.
.TP
\fIValue\fP
The value associated to the key \fIKey\fP.
.SH DESCRIPTION
\fBaddauthelem\fP adds a new element in the hash table if there is not
already an element associated to the key \fIKey\fP.
Otherwise \fBaddauthelem\fP changes the value of the existing one.
\fBaddauthelem\fP stretches the hash table \fIHashTable\fP if its size
seems to be too small.
.br
.SH RETURN VALUE
\fBaddauthelem\fP returns a pointer to the element associated to the key \fIKey\fP.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"authash: hash key 0 error !"
.ft R
.RS
The key \fIKey\fP of the hash table must be a valid pointer.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "aut101.h"
   authtable \(**HashTable;
   void add_in_dictionary( Name )
     \(** Name;
   {
     addauthelem( HashTable, namealloc( Name ), 0 );
   }
   ...
   HashTable = createauthtable( 1000 );
   add_in_dictionary( "hello" );
   add_in_dictionary( "world" );
   ...
   destroyauthtable( HashTable );
.ft R
.fi
.SH SEE ALSO
.BR aut (1)
.BR destroyauthtable(3),
.BR resetauthtable(3),
.BR createauthtable(3),
.BR searchauthelem(3),
.BR delauthelem(3).


.so man1/alc_bug_report.1

