.\"   $Id: addHExpr.3,v 1.1 1999/05/31 17:30:16 alliance Exp $
.\" @(#)addHExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH ADDHEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBaddHExpr\fP \- adds a new argument at the head of an operator expression. 
.SH SYNOPSYS
.nf
#include "logmmm.h"
void addHExpr(expr1,expr2)
chain_list *expr1,*expr2;
.fi
.SH PARAMETERS
.TP 20
\fIexpr1\fP
expression that recieves \fIexpr2\fP.
.TP 20
\fIexpr2\fP
Argument to add (atomic or operator expression).
.SH DESCRIPTION
\fBaddHExpr()\fP adds \fIexpr2\fP at the head of the expression \fIexpr1\fP. This procedure doesn't make any simplifications. 
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr1,*expr2; 
expr1 = createExpr(OR);
addHExpr(expr1,createAtom("var1"));
expr2 = createExpr(OR);
addHExpr(expr2,createAtom("var1"));
addHExpr(expr2,createAtom("var2"));
addHExpr(expr1,expr2);
displayExpr(expr1);
/* it will display
(OR (OR var2 var1) var1)
*/
freeExpr(expr1);	/* don't free expr2 ! */
.fi
.SH ERROR
"addHExpr : error - bad argument
.br
\fIexpr1\fP must be an operator expression.
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR createAtom (3),
.BR notExpr (3),
.BR addQExpr (3),
.BR createBinExpr (3),
.BR createExpr (3),
.BR addQExpr(3),
.BR freeExpr(3).

.so man1/alc_bug_report.1

