.\"   $Id: addOutputCct.3,v 1.1 1999/05/31 17:30:16 alliance Exp $
.\" @(#)addOuputCct.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH ADDOUTPUTCCT 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBaddOuputCct\fP \- adds an ouput associated to a BDD in a circuit 
.SH SYNOPSYS
.nf
#include "logmmm.h"
void addOuputCct(pC,name,pBdd)
pCircuit pC;
char *name;
pNode pBdd;
.fi
.SH PARAMETERS
.TP 20
\fIpC\fP
Circuit 
.TP 20
\fIname\fP
name to add
.TP 20
\fIpBdd\fP
node to add
.SH DESCRIPTION
\fBaddOuputCct()\fP adds a new output associated to a \fIpBdd\fP. 
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
pCircuit pC;
chain_list *expr;

initializeBdd(SMALL_BDD);
pC = initializeCct("circuit 1",10,10);

addInputCct(pC,"a");
addInputCct(pC,"b");

	/* let's suppose that expr = (OR a b) */

addOuputCct(pC,"s1",one);
addOuputCct(pC,"s2",ablToBddCct(pC,expr));

displayBdd(pC,1)

/* it will display 
************* DISPLAY circuit 1 **********
INPUT = a	INDEX = 2
INPUT = b	INDEX = 3
--------- NUMBER OF INPUTS = 2
OUTPUT = s1	s1 = 1
OUTPUT = s2	s2 = (OR a b)
--------- NUMBER OF OUTPUTS = 2
******************************************
*/

destroyCct(pC);
destroyBdd(1);
.fi
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR addOutputCct (3),
.BR searchInputCct (3),
.BR addOutputCct (3).


.so man1/alc_bug_report.1

