.\"   $Id: addTH.3,v 1.1 1999/05/31 17:30:16 alliance Exp $
.\" @(#)addTH.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH ADDTH 3 "October 1, 1997" "ASIM/LIP6" "Hash table functions"
.so man1/alc_origin.1
.SH NAME
\fBaddTH\fP \- adds a new item in a hash table.
.SH SYNOPSYS
.nf
#include "logmmm.h"
void addTH(pTable,key,value)
pTH pTable;
char *key;
int value;
.fi
.SH PARAMETERS
.TP 20
\fIpTable\fP
Hash table.
.TP 20
\fIkey\fP
Key used by the hash coding function.
.TP 20
\fIvalue\fP
Associated value (pointer must be casted)
.SH DESCRIPTION
\fBaddTH()\fP adds a new item in \fIpTable\fP. If the key already exists, the old value is replaced by the new value. \fIValue\fP must be distinct from -1 (EMPTYTH) and -2 (DELETETH). The length of the table increases automatically when the length given in \fBcreateTH()\fP is insufficient.
.SH EXAMPLE
.nf
#include "mutnnn.h"
#include "logmmm.h"
pTH mytable; 
mytable = createTH(100); 
addTH(mytable,namealloc("var1"),0);
addTH(mytable,namealloc("var2"),1);
.fi
.SH ERROR
"addTH : error - value is EMPTYTH or DELETETH"
.br
The value must be distinct from -1 and -2.
.SH SEE ALSO
.BR log (1),
.BR tsh (1),
.BR createTH (3),
.BR destroyTH (3),
.BR searchTH (3),
.BR deleteTH (3),
.BR displayTH (3).

.so man1/alc_bug_report.1

