.\"   $Id: arp.3,v 1.1 1999/05/31 17:30:17 alliance Exp $
.\" @(#)arp.l 0.0 93/07/30 UPMC; Author : Xavier Picat & El housseine REJOUAN
.if t \{\
.XS \n%
.XE \}
.TH ARP 3 "October 1, 1997" "ASIM/LIP6" "ALLIANCE ARP LIBRARIES"
.SH NAME
arp \- routing and placement functions
.so man1/alc_origin.1
.SH DESCRIPTION
Here is the list of functions that contains the arp library
.TP 20
\fBSymbolicChannelRouter\fP
\- routes a given channel on symbolic grid
.TP 20
\fBOpenVerticalChannel\fP
\- open a channel inside a phfig_list
.TP 20
\fBPlace\fP
\- places the cells of a lofig_list
.SH SEE ALSO

.so man1/alc_bug_report.1

