.\"   $Id: bebus.3,v 1.1 1999/05/31 17:30:18 alliance Exp $
.\" @(#)bebus.2 108 Feb 15 1995 UPMC; Pirouz BAZARGAN SABET
.TH BEBUS 3 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"

.so man1/alc_origin.1
.SH NAME
.PP
\fBbebus\fP - BEH data structure

.SH DESCRIPTION
.PP
\fIbebus\fP is a data structure used in \fBBEH\fP to represent a one\-bit
bused output port. A port is considered as a bused output when its value
is set by at least one deconnectable driver from the inside of the circuit.
For an array, each element is represented by a single structure.
These are organized in the reverse order of the array\'s range declaration.
\fIbebus\fP has been designed to be used in a simply chained list.

.PP
A \fIbebus\fP structure is composed of the following fields.

.TP 25
\fI(char *) NAME\fP
the port\'s name. For an array\'s element, the name is the array\'s identifier
added to the element\'s index seperated by a \' \' (blank space).
This string is supposed been produced by \fBnamealloc()\fP
.TP 25
\fI(char) TYPE\fP
port\'s type : W (wor_bit) and, M (mux_bit)
.TP 25
\fI(struct biabl *) BIABL\fP
list of drivers using ABLs to represent expressions
.TP 25
\fI(struct binode *) BINODE\fP
list of drivers using BDDs to represent expressions
.TP 25
\fI(struct bebus *) NEXT\fP
next port

.SH SEE ALSO
.PP
log(1), beh(3), biabl(3), binode(3), beh_addbebus(3),
beh_delbebus(3), beh_frebebus(3), beh_rmvbebus(3), namealloc(3)


.so man1/alc_bug_report.1

