.\"   $Id: bepor.3,v 1.1 1999/05/31 17:30:19 alliance Exp $
.\" @(#)bepor.2 108 Feb 15 1995 UPMC; Pirouz BAZARGAN SABET
.TH BEPOR 3 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"

.so man1/alc_origin.1
.SH NAME
.PP
\fBbepor\fP - BEH data structure

.SH DESCRIPTION
.PP
\fIbepor\fP is a data structure used in \fBBEH\fP to represent a one\-bit
port. A \fBbepor\fP list must be ordered in the reverse order of the port
declarations in the text file. For an array, each element is represented
by a single structure. These are organized in the reverse order of the
array\'s range declaration. \fIbepor\fP has been designed to be used in a
simply chained list.

.PP
A \fIbepor\fP structure is composed of the following fields.

.TP 25
\fI(char *) NAME\fP
the port\'s name. For an array\'s element, the name is the array\'s identifier
added to the element\'s index seperated by a \' \' (blank space).
This string is supposed been produced by \fBnamealloc()\fP
.TP 25
\fI(char) DIRECTION\fP
port\'s mode : I (input), O (output), Z (bused output), B (inout) and,
T (bused inout)
.TP 25
\fI(char) TYPE\fP
port\'s type : B (bit), M (mux_bit) and, W (wor_bit)
.TP 25
\fI(struct bepor *) NEXT\fP
next port

.SH SEE ALSO
.PP
beh(3), beh_addbepor(3), beh_delbepor(3), beh_frebepor(3), beh_rmvbepor(3),
namealloc(3)


.so man1/alc_bug_report.1

