.\"   $Id: binod.3,v 1.1 1999/05/31 17:30:19 alliance Exp $
.\" @(#)binode.2 107 Jun 30 1994 UPMC; Pirouz BAZARGAN SABET
.TH BINOD 3 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"

.so man1/alc_origin.1
.SH NAME
.PP
\fBbinode\fP - BEH data structure

.SH DESCRIPTION
.PP
\fIbinode\fP is a data structure used in \fBBEH\fP to represent a deconnectable
driver. \fIbinode\fP has been designed to be used in a simply chained list.

.PP
A \fIbinode\fP structure is composed of the following fields.

.TP 25
\fI(struct node *) CNDBDD\fP
connection codition of the driver expressed with a BDD
.TP 25
\fI(struct node *) VALBDD\fP
value emitted by the driver expressed with an BDD
.TP 25
\fI(struct binode *) NEXT\fP
next binode

.SH SEE ALSO
.PP
log(1), beh(3), beh_addbinode(3), beh_delbinode(3), beh_frebinode(3)


.so man1/alc_bug_report.1

