.\"   $Id: changeOperExpr.3,v 1.1 1999/05/31 17:30:19 alliance Exp $
.\" @(#)changeOperExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH CHANGEOPEREXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBchangeOperExpr\fP \- changes the operator of the head of an expression.
.SH SYNOPSYS
.nf
#include "logmmm.h"
void changeOperExpr(expr,oper)
chain_list *expr;
short oper;
.fi
.SH PARAMETERS
.TP 20
\fIexpr\fP
expression
.TP 20
\fIoper\fP
the new operator of the expression
.SH DESCRIPTION
\fBchangeOperExpr()\fP changes the operator of the head of \fIexpr\fP with \fIoper\fP.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr; 
expr = createExpr(OR);
addQExpr(expr,createAtom("a"));
addQExpr(expr,createAtom("b"));
displayExpr(expr);
changeOperExpr(expr, NAND);
displayExpr(expr);
/* it will display
 (or a b)
 (nand a b)
*/
freeExpr(expr);
.fi
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR searchExpr (3),
.BR searchOperExpr (3),
.BR searchNumExpr (3),
.BR equalExpr (3),
.BR equalVarExpr (3),
.BR lengthExpr (3),
.BR profExpr (3),
.BR numberAtomExpr (3).

.so man1/alc_bug_report.1

