.\"   $Id: charToExpr.3,v 1.1 1999/05/31 17:30:19 alliance Exp $
.\" @(#)charToExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH CHARTOEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBcharToExpr\fP \- converts a string into an expression 
.SH SYNOPSYS
.nf
#include "logmmm.h"
chain_list *charToExpr(stringExpr)
char *stringExpr;
.fi
.SH PARAMETERS
.TP 20
\fIstringExpr\fP
String to convert. 
.SH DESCRIPTION
\fBcharToExpr()\fP converts \fIstringExpr\fP into an expression.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
displayExpr(charToExpr("(nor a (and b c))"));
displayInfExpr(charToExpr("(nor a (and b c))"));
/* it will display
(nor a (and b c))
(a nor (b and c))
*/
.fi
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR exprToChar (3),
.BR displayExpr (3),
.BR displayInfExpr (3),
.BR charToOper (3),
.BR operToChar (3),
.BR identExpr (3).

.so man1/alc_bug_report.1

