.\"   $Id: composeCct.3,v 1.1 1999/05/31 17:30:19 alliance Exp $
.\" @(#)composeCct.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH COMPOSECCT 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBcomposeCct\fP \- composes all the outputs within a circuit with a BDD
.SH SYNOPSYS
.nf
#include "logmmm.h"
void composeCct(pC,name,pBdd)
pCircuit pC;
char *name;
pNode pBdd;
.fi
.SH PARAMETERS
.TP 20
\fIpC\fP
Circuit in which is made the composition
.TP 20
\fIname\fP
name to substitute
.TP 20
\fIpBdd\fP
BDD that replaces the variable
.SH DESCRIPTION
\fBcomposeCct()\fP substitutes the nodes associated to \fIname\fP by \fIpBdd\fP within \fIpC\fP.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr;
pNode res;
pCircuit pC;

initializeBdd(SMALL_BDD);
pC = initializeCct("circuit 1",10,10);

addInputCct(pC,"a");
addInputCct(pC,"b");

addOutputCct(pC,"s",applyBinBdd(OR,
                        createNodeTermBdd(searchInputCct(pC,"a")),
                        createNodeTermBdd(searchInputCct(pC,"b"))));

	/* a is replaced by (not b) */

composeCct(pC,"a",notBdd(createNodeTermBdd(searchInputCct(pC,"b"))));

displayCct(pC,1);

/* it will display 
************* DISPLAY circuit 1 *********
INPUT = b	INDEX = 3
----------- NUMBER OF INPUTS = 1
OUTPUT = s	s = 1
----------- NUMBER OF OUTPUTS = 1
*****************************************
*/

destroyCct(pC);
destroyBdd(1);
.fi
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR abl (1),
.BR upVarCct (3),
.BR constraintCct (3).

.so man1/alc_bug_report.1

