.\"   $Id: createTH.3,v 1.1 1999/05/31 17:30:19 alliance Exp $
.\" @(#)createTH.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH CREATETH 3 "October 1, 1997" "ASIM/LIP6" "Hash table functions"
.so man1/alc_origin.1
.SH NAME
\fBcreateTH\fP \- create a hash table
.SH SYNOPSYS
.nf
#include "logmmm.h"
pTH createTH(len)
int len;
.fi
.SH PARAMETER
.TP 20
\fIlen\fP
Length of the hash table.
.SH DESCRIPTION
\fBcreateTH()\fP creates a hash table in memory. \fIlen\fP is an estimate of the maximum number of entries that the table will contain. This number may be adjusted by a dynamic reallocation.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
pTH mytable; 
mytable = createTH(100);      	/* easy to make */
.fi
.SH ERROR
"createTH : error length <= 0"
.br
Hash table can't be created with length <= 0.
.SH SEE ALSO
.BR log (1),
.BR tsh (1),
.BR destroyTH (3),
.BR searchTH (3),
.BR addTH (3),
.BR deleteTH (3),
.BR displayTH(3).

.so man1/alc_bug_report.1

