.\"   $Id: deleteNumExpr.3,v 1.1 1999/05/31 17:30:20 alliance Exp $
.\" @(#)deleteNumExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH DELETENUMEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBdeleteNumExpr\fP \- removes the i-th argument of an operator expression. 
.SH SYNOPSYS
.nf
#include "logmmm.h"
void deleteNumExpr(expr,i)
chain_list *expr;
int i;
.fi
.SH PARAMETERS
.TP 20
\fIexpr\fP
expression
.TP 20
\fIi\fP
index of the argument
.SH DESCRIPTION
\fBdeleteNumExpr()\fP removes the \fIi-th\fP argument of \fIexpr\fP. As the array structures of C-programming, the index of the first argument is 0.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr; 
expr = createExpr(OR);
addQExpr(expr,createAtom("a"));
addQExpr(expr,createAtom("b"));
deleteNumExpr(expr,1);
displayExpr(expr);
/* it will display
(OR a)
*/
freeExpr(expr);
.fi
.SH ERROR
"deleteNumExpr : error - index out of bound"
.br
index i must be included between 0 and \fIlengthExpr(expr)-1\fP.
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR searchNumExpr (3),
.BR searchOperExpr (3),
.BR equalExpr (3),
.BR equalVarExpr (3),
.BR lengthExpr (3),
.BR profExpr (3),
.BR numberAtomExpr (3),
.BR numberOccExpr (3).

.so man1/alc_bug_report.1

