.\"   $Id: destroyauthtable.3,v 1.1 1999/05/31 17:30:20 alliance Exp $
.\" @(#)destroyauthtable.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH DESTROYAUTHTABLE 3 "October 1, 1997" "ASIM/LIP6" "AUT FUNCTIONS"
.SH NAME
destroyauthtable \- destroys a simple hash table.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "aut101.h"
void destroyauthtable( HashTable )
  authtable \(**HashTable;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIHashTable\fP
Pointer to the hash table to destroy.
.SH DESCRIPTION
\fBdestroyauthtable\fP destroys an hash table.
.br
.SH RETURN VALUE
\fBdestroyauthtable\fP returns nothing.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "aut101.h"
   authtable \(**HashTable;
   HashTable = createauthtable( 1000 );
   ...
   destroyauthtable( HashTable );
.ft R
.fi
.SH SEE ALSO
.BR aut (1)
.BR createauthtable(3),
.BR resetauthtable(3),
.BR addauthelem(3),
.BR searchauthelem(3),
.BR delauthelem(3).


.so man1/alc_bug_report.1

