.\"   $Id: destroyCct.3,v 1.1 1999/05/31 17:30:20 alliance Exp $
.\" @(#)destroyCct.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH DESTROYCCT 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBdestroyCct\fP \- removes a circuit 
.SH SYNOPSYS
.nf
#include "logmmm.h"
void destroyCct(pC)
pCircuit pC;
.fi
.SH PARAMETER
.TP 20
\fIpC\fP
circuit to remove
.SH DESCRIPTION
\fBdestroyCct()\fP removes a circuit.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
pCircuit pC;

initializeBdd(SMALL_BDD);
pC = initializeCct("circuit 1",10,10);

	/* application using pC */

destroyCct(pC);
destroyBdd(1);
.fi
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR resetCct (3),
.BR initializeCct (3).

.so man1/alc_bug_report.1

