.\"   $Id: destroyTH.3,v 1.1 1999/05/31 17:30:20 alliance Exp $
.\" @(#)destroyTH.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH DESTROYTH 3 "October 1, 1997" "ASIM/LIP6" "Hash table functions"
.so man1/alc_origin.1
.SH NAME
\fBdestroyTH\fP \- removes a hash table
.SH SYNOPSYS
.nf
#include "logmmm.h"
void destroyTH(pTable)
pTH pTable;
.fi
.SH PARAMETER
.TP 20
\fIpTable\fP
Hash table.
.SH DESCRIPTION
\fBdestroyTH()\fP removes \fIptable\fP in memory.
.SH EXAMPLE
.nf
#include "mutnnn.h"
#include "logmmm.h"
pTH mytable; 
mytable = createTH(100);
destroyTH(myTable);    
.fi
.SH SEE ALSO
.BR log (1),
.BR tsh (1),
.BR createTH (3),
.BR searchTH (3),
.BR addTH (3),
.BR deleteTH (3),
.BR displayTH(3).

.so man1/alc_bug_report.1

