.\"   $Id: destroyauth2table.3,v 1.1 1999/05/31 17:30:20 alliance Exp $
.\" @(#)destroyauth2table.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH DESTROYAUTH2TABLE 3 "October 1, 1997" "ASIM/LIP6" "AUT FUNCTIONS"
.SH NAME
destroyauth2table \- destroys an hash table with two keys.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "aut101.h"
void destroyauth2table( HashTable )
  auth2table \(**HashTable;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIHashTable\fP
Pointer to the hash table to destroy.
.SH DESCRIPTION
\fBdestroyauth2table\fP destroys an hash table.
.br
.SH RETURN VALUE
\fBdestroyauth2table\fP returns nothing.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "aut101.h"
   auth2table \(**HashTable;
   HashTable = createauth2table( 1000 );
   ...
   destroyauth2table( HashTable );
.ft R
.fi
.SH SEE ALSO
.BR aut (1)
.BR createauth2table(3),
.BR resetauth2table(3),
.BR addauth2elem(3),
.BR searchauth2elem(3),
.BR delauth2elem(3).


.so man1/alc_bug_report.1

