.\"   $Id: DP_ADSB2.3,v 1.1 1999/05/31 17:30:15 alliance Exp $
.TH DP_ADSB2 3 "October 1, 1997" "ASIM/LIP6" "FITPATH Macro-Functions"
.so man1/alc_origin.1
.SH NAME
\fBDP_ADSB2\fP - adder-substractor
.LP
.SH SYNOPSYS
.ft CR
.nf
#include  <fpgen.h>
void  DP_ADSB2( 
    char *InstName,  /*          Instance name           */

    char *BusI0,     /* IN       First Operand      DATA */
    char *BusI1,     /* IN       Second Operand     DATA */
    char *SigOp,     /* IN            Codop         CTRL */ 
    char *SigCout,   /* OUT         Carry out(n)    CTRL */
    char *SigCovr ,  /* OUT   Previous carry(n-1)   CTRL */
    char *BusO, EOL);/* OUT       Result output     DATA */
.fi
.ft R
.SH ARGUMENTS
.ta  7mC 12m
.in +12m
.ti -12m
\fISigOp\fP	\fBCTRL\fR	This one bit signal indicates the operation
(addition or substraction).
.ta +2n +10n +2n
.br
	- low	 :   addition.
.br
	- high	 :   substraction.
.br
.ta  7mC 12m

.SH DESCRIPTION
.LP
.ta 4m +4n +15nR +2n +2n
	\fBDP_ADSB2\fP creates an adder-substracter that has a wide of \fIWidth\fP
bits and then instanciates it with the name \fIInstName\fP. The maximal
authorized value for \fIWidth\fP is the full width of the current 
data-path, set by the previous call to the function \fBDP_DEFLOFIG\fP.
In the layout the leaf cells are placed on the slices numbered from
\fISlice\fP to \fISlice\fB+\fIWidth\fB-1\fR (the bottom slice is 0).
.br
.SH EXAMPLE
.ft CR
.nf

    DP_ADSB2( "adsb20", 32, 
                         0, 
                        "input0[3:0]", 
                        "input1[3:0]", 
                            "op"     ,
                            "c31"     ,
                            "c30"     ,
                        "output[3:0]", EOL);
	
.fi
.ft R
.SH SEE ALSO
.ft B
fpgen(3), adsb2g(3), fplib(3), mbk(1)

.so man1/alc_bug_report.1

