.\"   $Id: DP_MUX3CD.3,v 1.1 1999/05/31 17:30:15 alliance Exp $
.TH DP_MUX3CD 3 "October 1, 1997" "ASIM/LIP6" "FITPATH Macro-Functions"
.so man1/alc_origin.1
.SH NAME
\fBDP_MUX3CD\fP - 3 input multiplexer.
.SH SYNOPSYS
.ft CR
.nf
#include  <fpgen.h>

void  DP_MUX3CD( 	
    char *InstName,  /*           Instance name           */
    long  Width   ,  /*          Number of bits           */
    long  Slice   ,  /*     Index of the bottom slice     */

    char *BusSel  ,  /*  IN    Input Select          CTRL */
    char *BusI0   ,  /*  IN    First Input           DATA */
    char *BusI1   ,  /*  IN   Second Input           DATA */
    char *BusI1   ,  /*  IN    Third Input           DATA */
    char *BusO    ,  /* OUT   Direct Result Output   DATA */
               EOL);
.fi
.ft R
.SH DESCRIPTION
.ta 4m +4n +2n +15n +2n
	\fBDP_MUX3CD\fP creates a 3 input multiplexer. It is build using a
\fIdual-CMOS\fP architecture. The signal \fIBusSel\fP select which input is
connected to the  output :
.nf
		-	\fIBusSel\fP equal "\fB00\fP"	:	\fIBusO\fP <= \fIBusI0\fP.
		-	\fIBusSel\fP equal "\fB01\fP"	:	\fIBusO\fP <= \fIBusI1\fP.
		-	\fIBusSel\fP equal "\fB10\fP"	:	\fIBusO\fP <= \fIBusI2\fP.
.fi
	\fBDP_MUX3CD\fP build an operator of \fIWidth\fP
bits and then instanciates it with the name \fIInstName\fP. The maximal
authorized value for \fIWidth\fP is the full width of the current 
data-path, set by the previous call to the function \fBDP_DEFLOFIG\fP.
In the layout the leaf cells are placed on the slices numbered from
\fISlice\fP to \fISlice\fB+\fIWidth\fB-1\fR (the bottom slice of the
whole data-path is numbered zero).
.br
.SH EXAMPLE
.ft CR
.nf
DP_MUX3CD("mux3cd_instance0", 32, 
                               0,  "bus_sel[1:0]" ,
                                  "input_i0[31:0]", 
                                  "input_i1[31:0]", 
                                  "input_i1[31:0]", 
                                  "output_o[31:0]", EOL);
.fi
.ft R
.SH SEE ALSO
.ft B
fpgen(1), dpr(1), genlib(1), mbk(1),
DP_DEFLOFIG(3), DP_SAVLOFIG(3), DP_LOCON(3), DP_IMPORT(3),
DP_INV(3), DP_BUSE(3), DP_AND2(3), DP_NAND2(3), DP_AND3(3), DP_NAND3(3),
DP_OR2(3), DP_NOR2(3), DP_OR3(3), DP_NOR3(3), DP_XOR2(3), DP_XNOR2(3),
DP_NAND2MASK(3), DP_NOR2MASK(3), DP_XNOR2MASK(3), DP_CONST(3),
DP_NMUX2CS(3), DP_MUX2CS(3), DP_MUX3CS(3), DP_MUX4CS(3), DP_MUX5CS(3),
DP_BUSE(3), DP_NBUSE(3), DP_ADD2F(3), DP_ADSB2F(3),
DP_SHIFT(3), DP_MULT(3), DP_MULTP(3), DP_NUL(3),
DP_PDFF(3), DP_PDFFR(3), DP_PDFFT(3), DP_PDFFRT(3),
DP_RFG1C0(3), DP_RFG1CC(3), DP_RFG2C0(3), DP_RFG2CC(3)
,


.so man1/alc_bug_report.1

