.\"   $Id: flatArityExpr.3,v 1.1 1999/05/31 17:30:21 alliance Exp $
.\" @(#)flatArityExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH FLATARITYEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBflatArityExpr\fP \- flattens the operators of an expression
.SH SYNOPSYS
.nf
#include "logmmm.h"
void *latArityExpr(expr)
chain_list *expr;
.fi
.SH PARAMETER
.TP 20
\fIexpr\fP
expression to flatten
.SH DESCRIPTION
\fBflatArityExpr()\fP removes the useless operators. This function doesn't make any simplifications.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr1,*expr2,*expr3; 
expr1 = createExpr(OR);
addQExpr(expr1,createAtom("a"));
addQExpr(expr1,createAtom("b"));
expr2 = createExpr(OR);
addQExpr(expr2,createAtom("a"));
addQExpr(expr2,createAtom("c"));
addQExpr(expr1,expr2);
expr3 = copyExpr(expr1);
flatArityExpr(expr3);
displayExpr(expr1);
displayExpr(expr3);
/* it will display
(OR a b (OR a c))
(OR a b a c)
*/
freeExpr(expr1);
freeExpr(expr3);
.fi
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR flatPolarityExpr (3),
.BR copyExpr (3),
.BR substExpr (3),
.BR substPhyExpr (3),
.BR maxExpr (3),
.BR minExpr (3),
.BR sortExpr (3),
.BR normExpr (3).

.so man1/alc_bug_report.1

