.\"   $Id: funpaseq.3,v 1.1 1999/05/31 17:30:21 alliance Exp $
.\" @(#)paseq.2 106 Sep 30 1996 UPMC ; VUONG Huu-Nghia 
.TH FUNPASEQ 3 "October 1, 1997" "ASIM/LIP6" "PAT functions"

.so man1/alc_origin.1
.SH NAME
.PP
\fBpat_addpaseq\fP

.SH SYNOPSYS
.PP
.nf
struct paseq *pat_addpaseq (lastpaseq)
struct paseq *lastpaseq;
.fi

.SH PARAMETERS
.PP
.TP 10
\fIlastpaseq\fP
pointer on the last paseq structure

.SH DESCRIPTION
.PP
A paseq is a data structure representing a whole sequence of simulation
patterns.

.PP
\fBpat_addpaseq()\fP adds an empty paseq structure at the top of a list of paseq
structures. The function returns the pointer of the new list.
No check is made by this function.

.SH EXAMPLE
.PP
.nf
#include <pat106.h>

struct paseq *list;

list = pat_addpaseq (list);
.fi

.SH SEE ALSO
.PP
libpat(3), paseq(3)


.so man1/alc_bug_report.1

