.\"   $Id: GENLIB_UNFLATTEN_LOFIG.3,v 1.1 2000/09/28 15:20:01 fred Exp $
.\" @(#)UNFLATTEN_LOFIG.3 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
UNFLATTEN_LOFIG
.XE \}
.TH UNFLATTEN_LOFIG 3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
\fBUNFLATTEN_LOFIG\fP \- creates a hierarchy level from instances in the current logical figure
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void UNFLATTEN_LOFIG(figurename, instancename, list_of_instances, 0)
char \(**figurename;
char \(**instancename;
char \(**list_of_instances;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETERS
.TP 20
\fIfigurename\fP
Name of the figure of the new hierarchy to be created
.TP
\fIinstancename\fP
Name to be given at the instanciation of \fIfigurename\fP into the current
structual figure
.TP
\fIlist_of_instances\fP
List of strings representing the instances to be inserted into the new figure
.SH DESCRIPTION
\fBUNFLATTEN_LOFIG\fP creates a new level of hierarchy, whose model name will
be \fIfigurename\fP, and instanciate it under the name \fIinstancename\fP in
the current figure.
The instances whose name belong to the \fIlist_of_instances\fP parameters are
added in the new figure, and destroyed from the current figure.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Create a figure to work on  \(**/
	DEF_LOFIG("mycell");
	.
	.
	.
	/\(** Place an instance \(**/
	LOINS("model","instance", "sig1", "sig2", EOL);
	/\(** flatten an instance \(**/
	UNFLATTEN_LOFIG("newfig", "newins", "instance", ..., 0);
	/\(** Save all that on disk \(**/
	SAVE_LOFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR FLATTEN_LOFIG (3).


.so man1/alc_bug_report.1

