.\"   $Id: GENLIB_LOAD_LOFIG.3,v 1.1 2000/09/28 15:19:53 fred Exp $
.\" @(#)LOAD_LOFIG.3 2.11 91/08/22 ; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
LOAD_LOFIG
.XE \}
.TH LOAD_LOFIG 3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
LOAD_LOFIG \- loads a netlist form disk and opens it as current figure
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void LOAD_LOFIG(cellname)
char \(**cellname;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETERS
.TP 20
\fIcellname\fP
Name of the cell which all futher calls to genlib logical functions will
work on 
.SH DESCRIPTION
\fBLOAD_LOFIG\fP loads a netlist from disk and defines it as current working
structural figure. 
This overrides the working figure initialized by \fBDEF_LOFIG\fP(3), if any.
So the next call to \fBSAVE_LOFIG\fP will save the cell called \fIcellname\fP.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Loads the figure to work on  \(**/
	LOAD_LOFIG("cell");
	/\(** Add an instance in cell \(**/
	LOINS("model","instance", "sig1", "sig2", "sig3", "vdd", "vss", EOL);
	/\(** Save all that on disk \(**/
	SAVE_LOFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR DEF_LOFIG (3).
.BR SAVE_LOFIG (3).


.so man1/alc_bug_report.1

