.\"   $Id: GETCPAT.3,v 1.1 1999/05/31 17:30:15 alliance Exp $
.\" @(#)LABEL.3 2.30  UPMC ; PITON D.
.TH GETCPAT 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBGETCPAT\fP, GENPAT Package

.so man1/alc_origin.1
.SH SYNOPSYS
.PP
.nf
GETCPAT();
.fi

.SH DESCRIPTION
.PP
Return the the current pattern number. As the current pattern number is set
by AFFECT, GETCPAT will return the number of the last modified line . 

.SH EXAMPLE
.PP
.nf
int t;
t = GETCPAT();
.fi

.SH SEE ALSO
.PP
genpat(1), pat(5), AFFECT(3)


.so man1/alc_bug_report.1

