.\"   $Id: INIT.3,v 1.1 1999/05/31 17:30:15 alliance Exp $
.\" @(#)INIT.3 2.30  UPMC ; VUONG H.N. & PITON D.
.TH INIT 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBINIT\fP, GENPAT Package

.so man1/alc_origin.1
.SH SYNOPSYS
.PP
.nf
INIT("pattern_nb","ident","value");
.fi

.SH PARAMETERS
.PP
.TP 10
\fIpattern_nb\fP
pattern number which may be either : integer (absolute pattern number) or +
integer (relative pattern number, the last modified pattern is the reference) .
.TP 10
\fIident\fP
Either the name of a bused register or a simple register. Path-name must be
specified by the syntax : instance1.instance11.name
.TP 10
\fIvalue\fP
The value associated with the signal which may be either a based number (ex.
0B011 or 0H3F) or a decimal.

.SH DESCRIPTION
.PP
Initialize registers at indicated values and set current pattern number.

.SH EXAMPLE
.PP
.nf
INIT("13","regt","0B1");
Before pattern 13, the register named regt receive "1"
result :
	regt <= B"1" ;
pat_13 : .............;

INIT("+3","y 3 downto 0","0xF");
At pattern +3, (current pattern), the vector y composed of 
y 3, y 2, y 1, y 0 is affected with the value 15 in decimal 
or F in hexadecimal.
.fi

.SH SEE ALSO
.PP
genpat(1), pat(5), AFFECT(3)


.so man1/alc_bug_report.1

