.\"   $Id: label.3,v 1.1 1999/05/31 17:30:22 alliance Exp $
.\" @(#)LABEL.2 1.9  UPMC ; VUONG H.N.
.TH LABEL 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBlabel\fP, GENPAT Package

.so man1/alc_origin.1
.SH SYNOPSYS
.PP
.nf
label("ident");
.fi

.SH PARAMETERS
.PP
.TP 10
\fIident\fP
The LABEL asked.

.SH DESCRIPTION
.PP
Gives ident as the label of the current line of patterns in the output file. The current line of pattern is the pattern where the next AFFECT will aplly. That means than a LABEL must be written BEFORE an AFFECT, on which pattern it will apply.

.SH EXAMPLE
.PP
.nf
label("foo");
.fi

.SH SEE ALSO
genpat(1), pat(5)

.so man1/alc_bug_report.1

