.\"   $Id: mapExpr.3,v 1.1 1999/05/31 17:30:23 alliance Exp $
.\" @(#)mapExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH MAPEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBmapExpr\fP \- applies a procedure to all arguments of an operator expression
.SH SYNOPSYS
.nf
#include "logmmm.h"
void mapExpr(func,expr)
void (*func)();
chain_list *expr;
.fi
.SH PARAMETERS
.TP 20
\fIfunc\fP
function to apply
.TP 20
\fIexpr\fP
expression
.SH DESCRIPTION
\fBmapExpr()\fP applies \fIfunc()\fP to all the arguments of \fIexpr\fP. \fIfunc()\fP must be a procedure (it returns \fIvoid\fP) and must have an expression as argument . 
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
				/*newDisplayExpr */

void newDisplayExpr(expr)
chain_list *expr;
{
if (ATOM(expr))
   printf(" %s",VALUE_ATOM(expr));
else
   {
   printf("(%s ",operToChar(OPER(expr)));
   mapExpr(newDisplayExpr,expr);
   printf(")");
   }
}
.fi
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR mapCarExpr (3),
.BR anyExpr (3),
.BR everyExpr (3).

.so man1/alc_bug_report.1

