.\"   $Id: normExpr.3,v 1.1 1999/05/31 17:30:23 alliance Exp $
.\" @(#)normExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH NORMEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBnormExpr\fP \- normalizes an expression 
.SH SYNOPSYS
.nf
#include "logmmm.h"
void normExpr(expr)
chain_list *expr;
.fi
.SH PARAMETER
.TP 20
\fIexpr\fP
expression to normalize
.SH DESCRIPTION
\fBnormExpr()\fP sorts recursively the arguments of an expression by using predefined rules. The operator expressions are sorted by increasing operator number and arity of the first level. The atomic expressions are put at the end of the operator expressions.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr1; 

/* let's suppose that expr1 = (AND a (XOR b c a) (NOT h) (AND e g) (OR b a)) */

normExpr(expr1);
displayExpr(expr1);

/* it will display
(AND (OR b a) (AND e g) (XOR b c a) (NOT h) a)
*/
freeExpr(expr1);
.fi
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR sortExpr (3),
.BR maxExpr (3),
.BR minExpr (3),
.BR copyExpr (3),
.BR substExpr (3),
.BR substPhyExpr (3),
.BR flatArityExpr (3),
.BR flatPolarityExpr (3).

.so man1/alc_bug_report.1

