.\"   $Id: numberNodeCct.3,v 1.1 1999/05/31 17:30:23 alliance Exp $
.\" @(#)numberNodeCct.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH NUMBERNODECCT 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBnumberNodeCct\fP \- counts the number of nodes used within a circuit
.SH SYNOPSYS
.nf
#include "logmmm.h"
int numberNodeCct(pC)
pCircuit pC;
.fi
.SH PARAMETER
.TP 20
\fIpC\fP
circuit on which the count is done 
.SH DESCRIPTION
\fBnumberNodeCct()\fP counts the nodes that are used in \fIpC\fP.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
pCircuit pC;
chain_list *expr;

displayBdd(SMALL_BDD);
pC = initializeCct("circuit 1",10,10);

addInputCct(pC,"a");
addInputCct(pC,"b");

	/* let's suppose that expr = (OR a (AND (NOT a) b)) */

addOuputCct(pC,"s1",one);
addOuputCct(pC,"s2",ablToBddCct(pC,expr));

printf("number of nodes of the circuit = %d",numberNodeCct(pC));

/* it will display 
number of nodes of the circuit = 2
*/

destroyCct(pC);
destroyBdd(1);
.fi
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR initializeCct (3),
.BR resetCct (3),
.BR cpOrderCct (3),
.BR destroyCct (3).

.so man1/alc_bug_report.1

