.\"   $Id: numberAtomExpr.3,v 1.1 1999/05/31 17:30:23 alliance Exp $
.\" @(#)numberAtomExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH NUMBERATOMEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBnumberAtomExpr\fP \- returns the number of atoms in an expression
.SH SYNOPSYS
.nf
#include "logmmm.h"
int numberAtomExpr(expr)
chain_list *expr;
.fi
.SH PARAMETER
.TP 20
\fIexpr\fP
expression
.SH DESCRIPTION
\fBnumberAtomExpr()\fP returns the number of atoms of \fIexpr\fP.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr1,*expr2;
expr1 = createExpr(OR);
addQExpr(expr1,createAtom("a"));
addQExpr(expr1,createAtom("b"));
expr2 = createExpr(OR);
addQExpr(expr2,createAtom("c"));
addQExpr(expr2,createAtom("d"));
addQExpr(expr1,expr2);
printf("%d",numberAtomExpr(expr1));
/* it will display
4
*/
freeExpr(expr1);		/* don't free expr2 ! */
.fi
.SH PROGRAM
.nf
int numberAtomExpr(expr)
chain_list *expr;
{
if (ATOM(expr))
   return(1)
else
   {
   int cpt = 0;
   while (expr = CDR(expr))
      cpt = cpt + numberAtomExpr(CAR(expr));
   return(cpt);
   }
} 
.fi
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR profExpr (3),
.BR lengthExpr (3),
.BR equalExpr (3),
.BR equalVarExpr (3),
.BR searchExpr (3),
.BR searchOperExpr (3).

.so man1/alc_bug_report.1

