.\"   $Id: pacom.3,v 1.1 1999/05/31 17:30:23 alliance Exp $
.\" @(#)pacom.2 106 Sep 30 1996 UPMC; Pirouz BAZARGAN SABET
.TH PACOM 3 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"

.so man1/alc_origin.1
.SH NAME
.PP
\fBpacom\fP - PAT data structure

.SH DESCRIPTION
.PP
\fIpacom\fP is a data structure used in \fBPAT\fP to represent a comment read
from the pattern description file to be reproduced in the result file at the
same place. \fIpacom\fP has been designed to be used in a simply chained list.

.PP
A \fIpacom\fP structure is composed of the following fields.

.TP 25
\fI(char *) TEXT\fP
the text of the comment
.TP 25
\fI(unsigned short) POSITION\fP
the number of statements (input\-output declaration or pattern) to be printed
before the comment line 
.TP 25
\fI(struct pacom *) NEXT\fP
next pacom

.SH SEE ALSO
.PP
libpat(3), pat(5)


.so man1/alc_bug_report.1

