.\"   $Id: paevt.3,v 1.1 1999/05/31 17:30:23 alliance Exp $
.\" @(#)paevt.2 106 Sep 30 1996 UPMC; Pirouz BAZARGAN SABET
.TH PAEVT 3 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"

.so man1/alc_origin.1
.SH NAME
.PP
\fBpaevt\fP - PAT data structure

.SH DESCRIPTION
.PP
\fIpaevt\fP is a data structure used in \fBPAT\fP to represent an event on
a one\-bit input\-output.

.PP
For an input, a modification of the value forced on the port between two
consecutive patterns is considered as an event.

.PP
For an output, a modification of the value predicted for the output by the
user between two consecutive patterns is considered as an event. In
addition, whatever the last value of the output would be, it is considered
as an event, when no value has been predicted by the user (see pat(5)).

.PP
\fIpaevt\fP has been designed to be used in a simply chained list.

.PP
A \fIpaevt\fP structure is composed of the following fields.

.TP 20
\fI(unsigned short) INDEX\fP
the offset of the input\-output in the \fIpaiol\fP table
.TP 20
\fI(char) USERVAL\fP
value to be forced on the input or predicted for the output
.TP 20
\fI(char) SIMVAL\fP
value resulted from the simulation
.TP 20
\fI(struct paevt *) NEXT\fP
next paevt

.SH SEE ALSO
.PP
libpat(3), pat(5)


.so man1/alc_bug_report.1

