.\"   $Id: paini.3,v 1.1 1999/05/31 17:30:23 alliance Exp $
.\" @(#)paini.2 106 Sep 30 1996 UPMC; Pirouz BAZARGAN SABET
.TH PAINI 3 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"

.so man1/alc_origin.1
.SH NAME
.PP
\fBpaini\fP - PAT data structure

.SH DESCRIPTION
.PP
\fIpaini\fP is a data structure used in \fBPAT\fP to represent the
initialization of a one\-bit register. \fIpaini\fP has been designed to be
used in a simply chained list.

.PP
A \fIpaini\fP structure is composed of the following fields.

.TP 20
\fI(char *) NAME\fP
the register\'s name. For an array\'s element, the name is the array\'s
identifier added to the element\'s index separated by a \' \' (blank space).
This string is supposed been produced by \fBnamealloc()\fP.
.TP 20
\fI(char) VALUE\fP
value to be forced into the register
.TP 20
\fI(struct paini *) NEXT\fP
next paini

.SH SEE ALSO
.PP
libpat(3), pat(5), namealloc(3)


.so man1/alc_bug_report.1

