.\"   $Id: papat.3,v 1.1 1999/05/31 17:30:23 alliance Exp $
.\" @(#)papat.2 106 Sep 30 1996 UPMC; Pirouz BAZARGAN SABET
.TH PAPAT 3 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"

.so man1/alc_origin.1
.SH NAME
.PP
\fBpapat\fP - PAT data structure

.SH DESCRIPTION
.PP
\fIpapat\fP is a data structure used in \fBPAT\fP to represent a pattern.
A pattern is a set of values either forced at the same time on the inputs or
predicted for the outputs after the simulation step. \fIpapat\fP has been
designed to be used in a simply chained list.

.PP
A \fIpapat\fP structure is composed of the following fields.

.TP 20
\fI(char *) LABEL\fP
the label of the pattern (set to NULL if not present in the description file).
This string is supposed been produced by \fBnamealloc()\fP
.TP 20
\fI(unsigned short) LINE\fP
the location (line number) of the pattern in the pattern description file
.TP 20
\fI(char) BLANK\fP
number of empty lines to be printed after the pattern (up to 15)
.TP 20
\fI(char) ACTFLAG\fP
a flag representing the action associated with the pattern: I (initialize
registers before processing the pattern) and, U (no action)
.TP 20
\fI(char) SIMFLAG\fP
simulation flag : S (pattern already processed) and, U (pattern not yet
processed)
.TP
\fI(struct paevt *) PAEVT\fP
list of events
.TP
\fI(struct paini *) PAINI\fP
list of initialized registers
.TP 20
\fI(struct papat *) NEXT\fP
next papat

.SH SEE ALSO
.PP
libpat(3), pat(5), paevt(3), paini(3)


.so man1/alc_bug_report.1

