.\"   $Id: paseq.3,v 1.1 1999/05/31 17:30:23 alliance Exp $
.\" @(#)paseq.2 106 Sep 30 1996 UPMC; Pirouz BAZARGAN SABET
.TH PASEQ 3 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"

.so man1/alc_origin.1
.SH NAME
.PP
\fBpaseq\fP - PAT data structure

.SH DESCRIPTION
.PP
\fIpaseq\fP is a data structure used in \fBPAT\fP to represent a whole
sequence of simulation patterns. \fIpaseq\fP has been designed to be used
in a simply chained list.

.PP
A \fIpaseq\fP structure is composed of the following fields.

.TP 25
\fI(struct pagrp *) PAGRP\fP
list of actual or virtual arraies
.TP 25
\fI(struct paiol *) PAIOL\fP
list of inputs\-outputs
.TP 25
\fI(unsigned short) IOLNBR\fP
number of inputs\-outputs
.TP 25
\fI(struct pacom *) DECCOM\fP
list of comments (declaration part) to be printed in the result file
.TP 25
\fI(struct papat *) OLDPAT\fP
old patterns' list
.TP 25
\fI(struct pacom *) OLDCOM\fP
old comments
.TP 25
\fI(struct papat *) CURPAT\fP
current patterns' list
.TP 25
\fI(unsigned int) PATNBR\fP
number of patterns in the current patterns' list
.TP 25
\fI(struct pacom *) CURCOM\fP
current comments
.TP 25
\fI(struct papat *) NXTPAT\fP
next pattern
.TP 25
\fI(unsigned short) SUBSEQ\fP
number of the present patterns' sub-sequence in partial loading mode
.TP 25
\fI(unsigned short) DRVSEQ\fP
number of the last drived sub-sequence
.TP 25
\fI(unsigned int) LINENO\fP
current line number in the pattern file
.TP 25
\fI(char) SAVFLG\fP
is set to 'Y' if a save action is asked
.TP 25
\fI(char) ENDFLG\fP
is set to 'Y' if the end of the file is reached
.TP 25
\fI(char) ERRFLG\fP
contains a non zero value for a erroneous description
.TP 25
\fI(char) FLAGS\fP
contains some flags on the type of the sequence of patterns. The
\fBPAT_SEQ__IOLARRAY\fP flag is set when the input-output list is organized
as an array
.TP 25
\fI(struct paseq *) NEXT\fP
next paseq

.SH SEE ALSO
.PP
libpat(3), pat(5), pacom(3), pagrp(3), paiol(3), papat(3)


.so man1/alc_bug_report.1

