.\"   $Id: PMExpr.3,v 1.1 1999/05/31 17:30:16 alliance Exp $
.\" @(#)PMExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH PMEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBPMExpr\fP \- returns 1 if the pattern matching is possible between two expressions.
.SH SYNOPSYS
.nf
#include "logmmm.h"
int PMExpr(expr, pattern)
chain_list *expr,*pattern;
.fi
.SH PARAMETERS
.TP 20
\fIexpr\fP
first expression
.TP 20
\fIpattern\fP
pattern expression
.SH DESCRIPTION
\fBPMExpr()\fP returns 1 if the pattern matching is OK between \fIexpr\fP and \fIpattern\fP , in any other case, 0 is returned.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr1,*expr2; 

expr1 = charToExpr("(or (and a b) (xor a d))");
expr2 = charToExpr("(or (and x y) z)");
printf("%d\n",PMExpr(expr1,expr2));
/* it will display
1
*/
freeExpr(expr2);
expr2 = charToExpr("(or (and x y) (xor x y))");
printf("%d\n",PMExpr(expr1,expr2));
/* it will display
0
*/
freeExpr(expr1);
freeExpr(expr2);
.fi
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR equalExpr (3),
.BR equalVarExpr (3),
.BR searchExpr (3),
.BR searchOperExpr (3),
.BR lengthExpr (3),
.BR profExpr (3),
.BR numberAtomExpr (3).

.so man1/alc_bug_report.1

