.\"   $Id: register.3,v 1.1 1999/05/31 17:30:24 alliance Exp $
.\" @(#)REGISTER.2 1.9  UPMC ; VUONG H.N.
.TH REGISTER 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBregister\fP, GENPAT Package

.so man1/alc_origin.1
.SH SYNOPSYS
.PP
.nf
register("ident","ident", ... ,":nb_space","format","size",0);
.fi

.SH PARAMETERS
.PP
.TP 10
\fIident\fP
Register's name, the number of character is limited to 20
.TP 10
\fInb_space\fP
Specify the number of blank space between each group of value. 0,1,2,3,4,5,6,7,8,9 or nothing.
.TP 10
\fIformat\fP
Specify the format that will be used to represent the value associated to
the connectors. X for Hexadecimal, O for Octal and B for Binary.
.TP 10
\fIsize\fP
Specify the size of the bused connectors. ' ' : empty, (the chain is empty and the " are omitted) for the scalar
connectors, nb1 for the numbered connectors, nb1 TO nb2 (nb1 < nb2, nb1 and
nb2 integers), nb1 DOWNTO nb2 (nb2 < nb1).

.SH DESCRIPTION
.PP
Describes a set of internal registers of the same format and size.

.SH EXAMPLE
.PP
.nf
register("a","b","c","d",":2","X","3 DOWNTO 0",0);
describes : a 3, a 2, a 1, a 0, b 3, b 2, b 1, b 0, c 3, c 2, c 1, c 0, d
3, d 2, d 1, d 0.
format : Hexadecimal.
each group is separated of the others with 2 blank spaces.

register("toto",":","O","7 TO 11",0);
describes : toto 7, toto 8, toto 9, toto 10, toto 11.
format : Octal.
the group is separated of the following with 0 blank space.

register("ck",":2","B",0);
describes : ck.
format : Binary.
the register ck is separated of the following with 2 blank spaces.
.fi

.SH SEE ALSO
.PP
port(3), signal(3), genpat(1), pat(5)


.so man1/alc_bug_report.1

