.\"   $Id: resetCct.3,v 1.1 1999/05/31 17:30:24 alliance Exp $
.\" @(#)resetCct.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH RESETCCT 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBresetCct\fP \- resets a circuit 
.SH SYNOPSYS
.nf
#include "logmmm.h"
void resetCct(pC)
.fi
.SH PARAMETER
.TP 20
\fIpC\fP
circuit to reset
.SH DESCRIPTION
\fBresetCct()\fP resets a circuit.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
pCircuit pC;

initializeBdd(SMALL_BDD);
pC = initializeCct("circuit 1",10,10);

	/* first application using pC */

resetCct(pC);

	/* second application using pC */

destroyCct(pC);
destroyBdd(1);
.fi
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR initializeCct (3),
.BR destroyCct (3).

.so man1/alc_bug_report.1

