.\"   $Id: sav_genpat.3,v 1.1 1999/05/31 17:30:24 alliance Exp $
.\" @(#)SAV_GENPAT.2 1.9 UPMC ; VUONG H.N.
.TH SAV_GENPAT 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBsav_genpat\fP, GENPAT Package

.so man1/alc_origin.1
.SH SYNOPSYS
.PP
.nf
sav_genpat();
.fi

.SH DESCRIPTION
.PP
Indicates the end of the description.

.SH EXAMPLE
.PP
.nf
sav_genpat();
.fi

.SH SEE ALSO
.PP
def_genpat(3).genpat(1), pat(5)


.so man1/alc_bug_report.1

