.\"   $Id: searchOutputCct.3,v 1.1 1999/05/31 17:30:24 alliance Exp $
.\" @(#)searchOuputCct.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH SEARCHOUTPUTCCT 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBsearchOuputCct\fP \- searches for the BDD associated to an output 
.SH SYNOPSYS
.nf
#include "logmmm.h"
pNode searchOuputCct(pC,name)
pCircuit pC;
char *name;
.fi
.SH PARAMETERS
.TP 20
\fIpC\fP
Circuit 
.TP 20
\fIname\fP
name to look for
.SH DESCRIPTION
\fBsearchOuputCct()\fP searches for the BDD asociated to \fIname\fP. This function returns NULL if the BDD doesn't exist. 
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
pCircuit pC;
chain_list *expr;

initializeBdd(SMALL_BDD);
pC = initializeCct("circuit 1",10,10);

addInputCct(pC,"a");
addInputCct(pC,"b");

	/* let's suppose that expr = (OR a b) */

addOuputCct(pC,"s",ablToBddCct(pC,expr));

res = searchOutputCct(pC,"s");
displayBdd(res,0);

/* it will display 
@res	LOW = @nodeA	HIGH = ONE
*/

destroyCct(pC);
destroyBdd(1);
.fi
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR searchOutputCct (3),
.BR searchInputCct (3),
.BR addOutputCct (3).

.so man1/alc_bug_report.1

