.\"   $Id: searchExpr.3,v 1.1 1999/05/31 17:30:24 alliance Exp $
.\" @(#)searchExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH SEARCHEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBsearchExpr\fP \- searches for a specific atom in an expression.
.SH SYNOPSYS
.nf
#include "logmmm.h"
int searchExpr(expr,name)
chain_list *expr;
char *name;
.fi
.SH PARAMETERS
.TP 20
\fIexpr\fP
expression
.TP 20
\fIname\fP
name to look for
.SH DESCRIPTION
\fBsearchExpr()\fP searches for \fIname\fP in \fIexpr\fP and returns 1 if \fIname\fP is an atom of \fBexpr\fP.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr; 
expr = createExpr(OR);
addQExpr(expr,createAtom("a"));
addQExpr(expr,createAtom("b"));
printf("%d",searchExpr(expr,"a"));
/* it will display
1
*/
freeExpr(expr);
.fi

.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR searchOperExpr (3),
.BR equalExpr (3),
.BR equalVarExpr (3),
.BR lengthExpr (3),
.BR profExpr (3),
.BR numberAtomExpr (3).


.so man1/alc_bug_report.1

