.\"   $Id: SETTUNIT.3,v 1.1 1999/10/25 08:03:16 simcity Exp $
.\" @(#)SETTUNIT.3 2.30  UPMC ; VUONG H.N. & PITON D.
.TH SETTUNIT 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBSETTUNIT\fP, GENPAT Package

.so man1/alc_origin.1
.SH SYNOPSYS
.PP
.nf
SETTUNIT ("time_unit");
.fi

.SH PARAMETERS
.PP
.TP 10
\fItime_unit\fP
: legal time_unit are fs, ps, ns, us and ms.

.SH DESCRIPTION
.PP
Set the pattern \fItime_unit\fP. Default \fItime_unit\fP is ps.

.SH EXAMPLE
.PP
.nf
SETTUNIT ("ps");
SETTUNIT ("fs");
.fi

.SH WARNING
.PP
The SETTUNIT function is a new function of the 4.0 release.
To generate a pattern file in an oldest pat format (3.5 release
and oldest), you may use a virtual time_unit : SETTUNIT ("vu").
In this case, the pattern file is generated without dates (the
dates specified with the AFFECT and INIT functions are used as
pattern numbers).

.SH SEE ALSO
.PP
genpat(1), pat(5)


.so man1/alc_bug_report.1
