.\"   $Id: substExpr.3,v 1.1 1999/05/31 17:30:25 alliance Exp $
.\" @(#)substExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH SUBSTEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBsubstExpr\fP \- copies an expression by substituting a given atom by an expression
.SH SYNOPSYS
.nf
#include "logmmm.h"
chain_list *substExpr(expr1,name,expr2)
chain_list *expr1;
char *name;
chain_list *expr2;
.fi
.SH PARAMETERS
.TP 20
\fIexpr1\fP
expression to copy
.TP 20
\fIname\fP
name to substitute
.TP 20
\fIexpr2\fP
expression  that will remplace \fIname\fP
.SH DESCRIPTION
\fBsubstExpr()\fP creates a new ABL by copying \fIexpr1\fP in wich each occurence of \fIname\fP is replaced by \fIexpr2\fP. \fIexpr2\fP is only copied, therefore it's possible to free it.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr1,*expr2,*expr3; 
expr1 = createExpr(OR);
addQExpr(expr1,createAtom("a"));
addQExpr(expr1,createAtom("b"));
expr2 = notExpr(createAtom("x"));
expr3 = substExpr(expr1,"a",expr2);
displayExpr(expr1);
displayExpr(expr3);
/* it will display
(OR a b)
(OR (NOT x) b)
*/
freeExpr(expr1);
freeExpr(expr2);
freeExpr(expr3);
.fi
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR substPhyExpr (3),
.BR copyExpr (3),
.BR flatArityExpr (3),
.BR flatPolarityExpr (3),
.BR maxExpr (3),
.BR minExpr (3),
.BR sortExpr (3),
.BR normExpr (3).

.so man1/alc_bug_report.1

