.\"   $Id: substPhyExpr.3,v 1.1 1999/05/31 17:30:25 alliance Exp $
.\" @(#)substPhyExpr.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH SUBSTPHYEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL functions"
.so man1/alc_origin.1
.SH NAME
\fBsubstPhyExpr\fP \- substitutes an atomic expression by an expression within an operator expression 
.SH SYNOPSYS
.nf
#include "logmmm.h"
void substPhyExpr(expr1,name,expr2)
chain_list *expr1;
char *name;
chain_list *expr2;
.fi
.SH PARAMETERS
.TP 20
\fIexpr1\fP
expression on wich the susbstition will be made
.TP 20
\fIname\fP
name to substitute
.TP 20
\fIexpr2\fP
expression  that will remplace \fIname\fP
.SH DESCRIPTION
\fBsubstPhyExpr()\fP replaces each occurence of \fIname\fP within \fIexpr1\fP by \fIexpr2\fP.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
chain_list *expr1,*expr2; 
expr1 = createExpr(OR);
addQExpr(expr1,createAtom("a"));
addQExpr(expr1,createAtom("b"));
expr2 = notExpr(createAtom("x"));
substPhyExpr(expr1,"a",expr2);
displayExpr(expr1);
/* it will display
(OR (NOT x) b)
*/
freeExpr(expr1);
freeExpr(expr2);
.fi
.SH SEE ALSO
.BR log (1),
.BR abl (1),
.BR substExpr (3),
.BR copyExpr (3),
.BR flatArityExpr (3),
.BR flatPolarityExpr (3),
.BR maxExpr (3),
.BR minExpr (3),
.BR sortExpr (3),
.BR normExpr (3).

.so man1/alc_bug_report.1

