#!/bin/sh
#
#	ecoff-cmp file1.o file2.o
#
ld -s -L -o /tmp/foo1.$$ $1 2>1 > /dev/null
ld -s -L -o /tmp/foo2.$$ $2 2>1 > /dev/null
tail +10c /tmp/foo1.$$ > /tmp/foo3.$$
tail +10c /tmp/foo2.$$ > /tmp/foo4.$$
cmp /tmp/foo3.$$ /tmp/foo4.$$
rm -f /tmp/foo[1234].$$
