/* Generated automatically by the program `genoutput'
from the machine description file `md'.  */

#include "config.h"
#include "rtl.h"
#include "regs.h"
#include "hard-reg-set.h"
#include "real.h"
#include "conditions.h"
#include "insn-flags.h"
#include "insn-config.h"

#ifndef __STDC__
#define const
#endif

#include "output.h"
#include "aux-output.c"

#ifndef INSN_MACHINE_INFO
#define INSN_MACHINE_INFO struct dummy1 {int i;}
#endif


char * const insn_template[] =
  {
    "cmp.qi %0,%1",
    "cmp.hi %0,%1",
    "cmp.si %0,%1",
    "cmp.sf %0,%1",
    "cmp.df %0,%1",
    "cmp.qi %0,#0",
    "cmp.hi %0,#0",
    "cmp.si %0,#0",
    "cmp.sf %0,#0",
    "cmp.df %0,#0",
    "mov.qi %0,%1",
    "mov.hi %0,%1",
    "mov.si %0,%1",
    "mov.sf %0,%1",
    "mov.df %0,%1",
    "ext.qi.hi %1,%0",
    "ext.qi.si %1,%0",
    "ext.hi.si %1,%0",
    "ext0.hi.si %1,%0",
    "ext0.qi.hi %1,%0",
    "ext0.qi.si %1,%0",
    "ext.sf.df %1,%0",
    "trunc.si.qi %1,%0",
    "trunc.si.hi %1,%0",
    "trunc.hi.qi %1,%0",
    "trunc.df.sf %1,%0",
    "float.qi.sf %1,%0",
    "float.hi.sf %1,%0",
    "float.si.sf %1,%0",
    "float.qi.df %1,%0",
    "float.hi.df %1,%0",
    "float.si.df %1,%0",
    "fix_trunc.sf.qi %1,%0",
    "fix_trunc.sf.hi %1,%0",
    "fix_trunc.sf.si %1,%0",
    "fix_trunc.df.qi %1,%0",
    "fix_trunc.df.hi %1,%0",
    "fix_trunc.df.si %1,%0",
    "fixuns.sf.qi %1,%0",
    "fixuns.sf.hi %1,%0",
    "fixuns.sf.si %1,%0",
    "fixuns.df.qi %1,%0",
    "fixuns.df.hi %1,%0",
    "fixuns.df.si %1,%0",
    "add.qi %0,%1,%2",
    "add.hi %0,%1,%2",
    "add.si %0,%1,%2",
    "add.sf %0,%1,%2",
    "add.df %0,%1,%2",
    "mul.qi %0,%1,%2",
    "mul.hi %0,%1,%2",
    "mul.si %0,%1,%2",
    "mul.sf %0,%1,%2",
    "mul.df %0,%1,%2",
    "div.qi %0,%1,%2",
    "div.hi %0,%1,%2",
    "div.si %0,%1,%2",
    "div.sf %0,%1,%2",
    "div.df %0,%1,%2",
    "sub.qi %0,%1,%2",
    "sub.hi %0,%1,%2",
    "sub.si %0,%1,%2",
    "sub.sf %0,%1,%2",
    "sub.df %0,%1,%2",
    "and.qi %0,%1,%2",
    "and.hi %0,%1,%2",
    "and.si %0,%1,%2",
    "or.qi %0,%1,%2",
    "or.hi %0,%1,%2",
    "or.si %0,%1,%2",
    "xor.qi %0,%1,%2",
    "xor.hi %0,%1,%2",
    "xor.si %0,%1,%2",
    "neg.qi %0,%1",
    "neg.hi %0,%1",
    "neg.si %0,%1",
    "not.qi %0,%1",
    "not.hi %0,%1",
    "not.si %0,%1",
    "asl.qi %0,%1,%2",
    "asl.hi %0,%1,%2",
    "asl.si %0,%1,%2",
    "asr.qi %0,%1,%2",
    "asr.hi %0,%1,%2",
    "asr.si %0,%1,%2",
    "lsl.qi %0,%1,%2",
    "lsl.hi %0,%1,%2",
    "lsl.si %0,%1,%2",
    "lsr.qi %0,%1,%2",
    "lsr.hi %0,%1,%2",
    "lsr.si %0,%1,%2",
    "beq %l0",
    "bne %l0",
    "bgt %l0",
    "bgtu %l0",
    "blt %l0",
    "bltu %l0",
    "bge %l0",
    "bgeu %l0",
    "ble %l0",
    "bleu %l0",
    "bne %l0",
    "beq %l0",
    "ble %l0",
    "bleu %l0",
    "bge %l0",
    "bgeu %l0",
    "blt %l0",
    "bltu %l0",
    "bgt %l0",
    "bgtu %l0",
    "bra %l0",
    "bra %0",
    "call %0",
    "call %1",
    "nop",
  };

char *(*const insn_outfun[])() =
  {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
  };

rtx (*const insn_gen_function[]) () =
  {
    gen_cmpqi,
    gen_cmphi,
    gen_cmpsi,
    gen_cmpsf,
    gen_cmpdf,
    gen_tstqi,
    gen_tsthi,
    gen_tstsi,
    gen_tstsf,
    gen_tstdf,
    gen_movqi,
    gen_movhi,
    gen_movsi,
    gen_movsf,
    gen_movdf,
    gen_extendqihi2,
    gen_extendqisi2,
    gen_extendhisi2,
    gen_zero_extendhisi2,
    gen_zero_extendqihi2,
    gen_zero_extendqisi2,
    gen_extendsfdf2,
    gen_truncsiqi2,
    gen_truncsihi2,
    gen_trunchiqi2,
    gen_truncdfsf2,
    gen_floatqisf2,
    gen_floathisf2,
    gen_floatsisf2,
    gen_floatqidf2,
    gen_floathidf2,
    gen_floatsidf2,
    gen_fix_truncsfqi2,
    gen_fix_truncsfhi2,
    gen_fix_truncsfsi2,
    gen_fix_truncdfqi2,
    gen_fix_truncdfhi2,
    gen_fix_truncdfsi2,
    gen_fixunssfqi2,
    gen_fixunssfhi2,
    gen_fixunssfsi2,
    gen_fixunsdfqi2,
    gen_fixunsdfhi2,
    gen_fixunsdfsi2,
    gen_addqi3,
    gen_addhi3,
    gen_addsi3,
    gen_addsf3,
    gen_adddf3,
    gen_mulqi3,
    gen_mulhi3,
    gen_mulsi3,
    gen_mulsf3,
    gen_muldf3,
    gen_divqi3,
    gen_divhi3,
    gen_divsi3,
    gen_divsf3,
    gen_divdf3,
    gen_subqi3,
    gen_subhi3,
    gen_subsi3,
    gen_subsf3,
    gen_subdf3,
    gen_andqi3,
    gen_andhi3,
    gen_andsi3,
    gen_iorqi3,
    gen_iorhi3,
    gen_iorsi3,
    gen_xorqi3,
    gen_xorhi3,
    gen_xorsi3,
    gen_negqi2,
    gen_neghi2,
    gen_negsi2,
    gen_one_cmplqi2,
    gen_one_cmplhi2,
    gen_one_cmplsi2,
    gen_ashlqi3,
    gen_ashlhi3,
    gen_ashlsi3,
    gen_ashrqi3,
    gen_ashrhi3,
    gen_ashrsi3,
    gen_lshlqi3,
    gen_lshlhi3,
    gen_lshlsi3,
    gen_lshrqi3,
    gen_lshrhi3,
    gen_lshrsi3,
    gen_beq,
    gen_bne,
    gen_bgt,
    gen_bgtu,
    gen_blt,
    gen_bltu,
    gen_bge,
    gen_bgeu,
    gen_ble,
    gen_bleu,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    gen_jump,
    gen_tablejump,
    gen_call,
    gen_call_value,
    gen_nop,
  };

const int insn_n_operands[] =
  {
    2,
    2,
    2,
    2,
    2,
    1,
    1,
    1,
    1,
    1,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    2,
    2,
    2,
    2,
    2,
    2,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    2,
    3,
    0,
  };

const int insn_n_dups[] =
  {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
  };

char *const insn_operand_constraint[][MAX_RECOG_OPERANDS] =
  {
    { "g", "g", },
    { "g", "g", },
    { "g", "g", },
    { "g", "g", },
    { "g", "g", },
    { "g", },
    { "g", },
    { "g", },
    { "g", },
    { "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "%g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { "=g", "g", "g", },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { "g", },
    { "g", "g", },
    { "g", "g", "g", },
    { 0 },
  };

const enum machine_mode insn_operand_mode[][MAX_RECOG_OPERANDS] =
  {
    { QImode, QImode, },
    { HImode, HImode, },
    { SImode, SImode, },
    { SFmode, SFmode, },
    { DFmode, DFmode, },
    { QImode, },
    { HImode, },
    { SImode, },
    { SFmode, },
    { DFmode, },
    { QImode, QImode, },
    { HImode, HImode, },
    { SImode, SImode, },
    { SFmode, SFmode, },
    { DFmode, DFmode, },
    { HImode, QImode, },
    { SImode, QImode, },
    { SImode, HImode, },
    { SImode, HImode, },
    { HImode, QImode, },
    { SImode, QImode, },
    { DFmode, SFmode, },
    { QImode, SImode, },
    { HImode, SImode, },
    { QImode, HImode, },
    { SFmode, DFmode, },
    { SFmode, QImode, },
    { SFmode, HImode, },
    { SFmode, SImode, },
    { DFmode, QImode, },
    { DFmode, HImode, },
    { DFmode, SImode, },
    { QImode, SFmode, },
    { HImode, SFmode, },
    { SImode, SFmode, },
    { QImode, DFmode, },
    { HImode, DFmode, },
    { SImode, DFmode, },
    { QImode, SFmode, },
    { HImode, SFmode, },
    { SImode, SFmode, },
    { QImode, DFmode, },
    { HImode, DFmode, },
    { SImode, DFmode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { SFmode, SFmode, SFmode, },
    { DFmode, DFmode, DFmode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { SFmode, SFmode, SFmode, },
    { DFmode, DFmode, DFmode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { SFmode, SFmode, SFmode, },
    { DFmode, DFmode, DFmode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { SFmode, SFmode, SFmode, },
    { DFmode, DFmode, DFmode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { QImode, QImode, },
    { HImode, HImode, },
    { SImode, SImode, },
    { QImode, QImode, },
    { HImode, HImode, },
    { SImode, SImode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { QImode, QImode, QImode, },
    { HImode, HImode, HImode, },
    { SImode, SImode, SImode, },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { VOIDmode },
    { SImode, },
    { SImode, SImode, },
    { VOIDmode, SImode, SImode, },
    { VOIDmode },
  };

const char insn_operand_strict_low[][MAX_RECOG_OPERANDS] =
  {
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, },
    { 0, },
    { 0, },
    { 0, },
    { 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0, 0, 0, },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0, },
    { 0, 0, },
    { 0, 0, 0, },
    { 0 },
  };

int (*const insn_operand_predicate[][MAX_RECOG_OPERANDS])() =
  {
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, },
    { general_operand, },
    { general_operand, },
    { general_operand, },
    { general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { general_operand, general_operand, general_operand, },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { 0 },
    { general_operand, },
    { ever_good, ever_good, },
    { 0, ever_good, ever_good, },
    { 0 },
  };

#ifndef DEFAULT_MACHINE_INFO
#define DEFAULT_MACHINE_INFO 0
#endif

const INSN_MACHINE_INFO insn_machine_info[] =
  {
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
     { DEFAULT_MACHINE_INFO },
  };

const int insn_n_alternatives[] =
  {
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
    1,
    1,
    1,
     0,
  };
