#!/bin/sh
#
# Filename: mkdistrib
# Copyright (C) 1999, 2000 Czo <Olivier.Sirol@lip6.fr>
# License: GPL (http://www.gnu.org/copyleft/gpl.html)
# Started: April 2000
# Last Change: Thursday 06 June 2002, 14:45
# Edit Time: 127:43:45
# Description:
#
# $Id: mkdistrib,v 1.3 2002/06/06 12:46:26 czo Exp $
#

###################################################################

DISTRIBDIR=/users/soft5/newlabo/distrib

WKSLIST="bip beny"
FTPDISTRIBDIR=/users/largo2/ftp/pub/alliance/unstable/distribution
LOGFILE=/tmp/albuild.$$

DATE=`date +%Y%m%d`

ALC_VER="5.0"
ALC_DIR="alliance-$ALC_VER"
ALC_PACK="$ALC_DIR-$DATE"

ALC_TMPDIR=tmp-$$
TMPBUILD=tmpbuild-$$
TMPINSTALL=tmpinstall-$$
TMPALLIANCE=alliance-tmp-$$

TMPDESTDIR=tmpdestdir-$$
TMPBUILDDIR=tmpbuilddir-$$

CVSROOT=/users/outil/alliance/cvsroot
export CVSROOT


###################################################################

fail() {
echo -e "\
                                                             \n\
                                                             \n\
                   @@@@@@@@@        @      @@@@@@ @@@@@@     \n\
                     @@    @        @        @@     @@       \n\
                     @@     @      @@@       @@     @@       \n\
                     @@            @@@       @@     @@       \n\
                     @@   @       @  @@      @@     @@       \n\
                     @@@@@@       @  @@      @@     @@       \n\
                     @@   @      @    @@     @@     @@       \n\
                     @@          @@@@@@@     @@     @@       \n\
                     @@         @      @@    @@     @@      @\n\
                     @@         @      @@    @@     @@     @ \n\
                   @@@@@@     @@@@    @@@@ @@@@@@ @@@@@@@@@@ "
echo ""
}

pass() {
echo -e "\
                                                              \n\
                                                              \n\
                   @@@@@@@          @        @@@@ @    @@@@ @ \n\
                     @@   @@        @       @    @@   @    @@ \n\
                     @@    @@      @@@     @@     @  @@     @ \n\
                     @@    @@      @@@     @@@       @@@      \n\
                     @@   @@      @  @@     @@@@      @@@@    \n\
                     @@@@@        @  @@       @@@@      @@@@  \n\
                     @@          @    @@        @@@       @@@ \n\
                     @@          @@@@@@@   @      @@ @      @@\n\
                     @@         @      @@  @@     @@ @@     @@\n\
                     @@         @      @@  @@@    @  @@@    @ \n\
                   @@@@@@     @@@@    @@@@ @  @@@@   @  @@@@  "
echo ""
}

try() {
$*
EXECEXIT=$?
if [ $EXECEXIT != 0 ] ; then 
  fail
  echo "TRYFAIL $*"
  exit $EXECEXIT
else
  echo "TRYOK $*"
fi

}

###################################################################
echo "--> mk-distrib"

try cd $DISTRIBDIR

echo "--> Removing old test..."
mkdir $ALC_TMPDIR
mv alliance* tmpdestdir-* tmpbuilddir-* $ALC_TMPDIR
rm -fr  $ALC_TMPDIR &

echo "--> Checkout CVS sources..."
cvs co -P -r TAG_DISTRIB alliance/src

echo "--> Makedist, generation de alliance-5.0.tar.gz"

try cd alliance/src

try ./autostuff
cd ..
mkdir $TMPBUILD
mkdir $TMPINSTALL
try cd $TMPBUILD

export ALLIANCE_TOP=$DISTRIBDIR/alliance/$TMPINSTALL

try ../src/configure --prefix=$ALLIANCE_TOP

try make install
try make distcheck

mv "$ALC_DIR.tar.gz" "$ALC_PACK.tar.gz"
cp -f "$ALC_PACK.tar.gz" $FTPDISTRIBDIR
mv -f "$ALC_PACK.tar.gz" ../..

cd ../..

mv alliance $TMPALLIANCE
(chmod -R 777 $TMPALLIANCE ; rm -fr $TMPALLIANCE)&

try tar -xvzf "$ALC_PACK.tar.gz"

for WKS in $WKSLIST
do

mkdir $TMPDESTDIR-$WKS $TMPBUILDDIR-$WKS
ssh -n $WKS "cd $DISTRIBDIR/$TMPBUILDDIR-$WKS ; \
export ALLIANCE_TOP=$DISTRIBDIR/$TMPDESTDIR-$WKS/usr/local/alliance; \
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% $ALLIANCE_TOP" ; \
../$ALC_DIR/configure --prefix=/usr/local/alliance ; \
make DESTDIR=$ALLIANCE_TOP install"  2>&1 | tee $LOGFILE

done

echo "done..."
echo "###########   O K pour tout le monde   #############"




