#!/bin/sh

DATE=`/asim/gnu/bin/date +"%Y.%m.%d_%H.%M.%S"`
LABO=/users/soft5/newlabo/alliance

for ARCHI in Linux_elf SunOS Solaris
 do
 for FILE in /users/outil1/alliance/alliance/archi/$ARCHI/bin/*
 do
    echo %%%%%% $FILE
    cp -f $FILE /users/soft5/newlabo/alliance/archi/$ARCHI/bin/`basename $FILE`.$DATE
    ln -f -s /users/soft5/newlabo/alliance/archi/$ARCHI/bin/`basename $FILE`.$DATE /users/soft5/newlabo/alliance/archi/$ARCHI/bin/`basename $FILE`
    done
  for TRUC in lib include
  do
    cp -f /users/outil1/alliance/alliance/archi/$ARCHI/$TRUC/* /users/soft5/newlabo/alliance/archi/$ARCHI/$TRUC
  done
 done

