#! /bin/sh
#
# Author      : Olivier.Sirol@lip6.fr
# Date        : dec 1998
# Description : 
#
# (C) Czo 1998,99
# This code is released under GPL
# $Id: multiconf,v 1.1 2000/09/22 15:03:48 czo Exp $
#


# I made this script to build alliance on multiple architectures
# Modify it to suit you site

# TODO : change this to a makefile...

#set +x
#set -x

TMPFILE=/tmp/albuild.$$

ALLIANCEDIR=`pwd`

for WKS in fusion fado fox

do
echo "Configuring $WKS..."
ssh -n $WKS "cd $ALLIANCEDIR; ./configure"  2>&1 | tee $TMPFILE
grep "^or .*whether you use csh or sh" $TMPFILE
if [ $? -ne 0 ] ; then echo "Error, $WKS, exiting" ; exit 4 ; fi
rm $TMPFILE
done

echo "done..."
echo "###########   O K pour tout le monde   #############"

