#!/bin/sh
#
# Autorun script for Red Hat Linux
# Copyright (c) 1999 Red Hat, Inc.

kdepid=`/sbin/pidof knotify`
konqueror=`/usr/bin/which konqueror` 2> /dev/null
mozilla=`/usr/bin/which netscape` 2> /dev/null

if [ -d /mnt/cdrom ]; then
  cd /mnt/cdrom
fi

if [ "$kdepid" = "" ]; then
  # they are running GNOME most likely, use mozilla
  if [ ! "$mozilla" = "" ]; then
    $mozilla file:/mnt/cdrom/Readme.html
  elif [ ! "$konqueror" = "" ]; then
    $konqueror file:/mnt/cdrom/Readme.html
  fi
else
  if [ ! "$konqueror" = "" ]; then
    $konqueror file:/mnt/cdrom/Readme.html
  elif [ ! "$mozilla" = "" ]; then
    $mozilla file:/mnt/cdrom/Readme.html
  fi
fi
